/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTemplatesCreateAgentTemplate } from "../../funcs/agentTemplatesCreateAgentTemplate.js";
import { CreateAgentTemplateRequest$zodSchema } from "../../models/createagenttemplateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateAgentTemplateRequest$zodSchema,
};

export const tool$agentTemplatesCreateAgentTemplate: ToolDefinition<
  typeof args
> = {
  name: "agent-templates-create-agent-template",
  description: `Create agent template

Create a new reusable agent template.<br><br>
<b>Overview:</b><br>
Templates define the base configuration for agents including
system prompts, tool recommendations, and customization options.<br><br>
<b>Template Components:</b><br>
<ul>
<li><b>System prompt:</b> Default instructions for agents</li>
<li><b>Recommended tools:</b> Suggested tool integrations</li>
<li><b>Config schema:</b> JSON Schema for customization options</li>
</ul>
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentTemplatesCreateAgentTemplate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
