/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorOAuthHandleOAuthCallback } from "../../funcs/connectorOAuthHandleOAuthCallback.js";
import { HandleOAuthCallbackRequest$zodSchema } from "../../models/handleoauthcallbackop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: HandleOAuthCallbackRequest$zodSchema.optional(),
};

export const tool$connectorOAuthHandleOAuthCallback: ToolDefinition<
  typeof args
> = {
  name: "connector-O-auth-handle-O-auth-callback",
  description: `OAuth callback handler

Handle the OAuth callback from the identity provider.<br><br>
<b>Note:</b><br>
This endpoint is called by the OAuth provider after user authentication.
The state parameter contains the encoded connector ID.<br><br>
<b>Success:</b><br>
On success, tokens are stored and the connector becomes authenticated.
User is redirected to the frontend success page.<br><br>
<b>Error:</b><br>
If the provider returns an error (e.g., user denied access),
user is redirected with error information.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await connectorOAuthHandleOAuthCallback(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
