/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsAddMessage } from "../../funcs/conversationsAddMessage.js";
import { AddMessageRequestRequest$zodSchema } from "../../models/addmessageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AddMessageRequestRequest$zodSchema,
};

export const tool$conversationsAddMessage: ToolDefinition<typeof args> = {
  name: "conversations-add-message",
  description: `Add message to conversation

Add a follow-up message to an existing conversation.<br><br>
<b>Overview:</b><br>
Continues an existing conversation by adding a new user query.
The AI maintains context from previous messages when generating the response.<br><br>
<b>Context Handling:</b><br>
<ul>
<li>Previous messages provide context for the new query</li>
<li>Citations from earlier messages may be referenced</li>
<li>The AI can refer back to previous topics discussed</li>
</ul>
<b>Model Override:</b><br>
You can specify a different model for this message using <code>modelKey</code>.
This allows switching models mid-conversation if needed.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await conversationsAddMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
