/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthConfigurationListOAuthConfigs } from "../../funcs/oAuthConfigurationListOAuthConfigs.js";
import { ListOAuthConfigsRequest$zodSchema } from "../../models/listoauthconfigsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListOAuthConfigsRequest$zodSchema.optional(),
};

export const tool$oAuthConfigurationListOAuthConfigs: ToolDefinition<
  typeof args
> = {
  name: "O-auth-configuration-list-O-auth-configs",
  description: `List OAuth configurations

List all OAuth configurations for the organization.<br><br>
<b>Security:</b><br>
<ul>
<li>Admins see full configuration including credentials</li>
<li>Non-admins see only essential fields (client ID, not secret)</li>
</ul>
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthConfigurationListOAuthConfigs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
