/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthProviderOauthAuthorizeConsent } from "../../funcs/oAuthProviderOauthAuthorizeConsent.js";
import { OAuthConsentRequest$zodSchema } from "../../models/oauthconsentrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: OAuthConsentRequest$zodSchema,
};

export const tool$oAuthProviderOauthAuthorizeConsent: ToolDefinition<
  typeof args
> = {
  name: "O-auth-provider-oauth-authorize-consent",
  description: `Submit authorization consent

Submit user's consent decision for OAuth authorization.
<br><br>
Called after user reviews the consent page and makes a decision.
This endpoint generates an authorization code if consent is granted.
<br><br>
<b>Responses:</b><br>
- Consent granted: Redirects to client with authorization code<br>
- Consent denied: Redirects to client with \`access_denied\` error
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthProviderOauthAuthorizeConsent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
