/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthAppsRevokeAllOAuthAppTokens } from "../../funcs/oAuthAppsRevokeAllOAuthAppTokens.js";
import { RevokeAllOAuthAppTokensRequest$zodSchema } from "../../models/revokealloauthapptokensop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RevokeAllOAuthAppTokensRequest$zodSchema,
};

export const tool$oAuthAppsRevokeAllOAuthAppTokens: ToolDefinition<
  typeof args
> = {
  name: "O-auth-apps-revoke-all-O-auth-app-tokens",
  description: `Revoke all app tokens

Revoke all tokens (access and refresh) issued to an OAuth app.
<br><br>
Use this for emergency access removal or when rotating credentials.
<br><br>
<b>Admin Only:</b> Requires admin privileges.
<br><br>
<b>Rate Limited:</b> 10 requests per minute.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthAppsRevokeAllOAuthAppTokens(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
