/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthAppsRegenerateOAuthAppSecret } from "../../funcs/oAuthAppsRegenerateOAuthAppSecret.js";
import { RegenerateOAuthAppSecretRequest$zodSchema } from "../../models/regenerateoauthappsecretop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RegenerateOAuthAppSecretRequest$zodSchema,
};

export const tool$oAuthAppsRegenerateOAuthAppSecret: ToolDefinition<
  typeof args
> = {
  name: "O-auth-apps-regenerate-O-auth-app-secret",
  description: `Regenerate client secret

Regenerate the client secret for an OAuth app.
<br><br>
The old secret is immediately invalidated. Any clients using the old
secret will fail to authenticate until updated with the new secret.
<br><br>
<b>Important:</b> The new secret is only returned once. Store it securely.
<br><br>
<b>Admin Only:</b> Requires admin privileges.
<br><br>
<b>Rate Limited:</b> 10 requests per minute.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthAppsRegenerateOAuthAppSecret(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
