/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthConfigurationGetOAuthConnectorType } from "../../funcs/oAuthConfigurationGetOAuthConnectorType.js";
import { GetOAuthConnectorTypeRequest$zodSchema } from "../../models/getoauthconnectortypeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetOAuthConnectorTypeRequest$zodSchema,
};

export const tool$oAuthConfigurationGetOAuthConnectorType: ToolDefinition<
  typeof args
> = {
  name: "O-auth-configuration-get-O-auth-connector-type",
  description: `Get OAuth connector type details

Get details for a specific OAuth-capable connector type.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthConfigurationGetOAuthConnectorType(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
