/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthConfigurationDeleteOAuthConfig } from "../../funcs/oAuthConfigurationDeleteOAuthConfig.js";
import { DeleteOAuthConfigRequest$zodSchema } from "../../models/deleteoauthconfigop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteOAuthConfigRequest$zodSchema,
};

export const tool$oAuthConfigurationDeleteOAuthConfig: ToolDefinition<
  typeof args
> = {
  name: "O-auth-configuration-delete-O-auth-config",
  description: `Delete OAuth configuration

Delete an OAuth configuration.<br><br>
<b>Warning:</b><br>
Cannot delete if the configuration is used by active connectors.
Disable or delete dependent connectors first.
`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthConfigurationDeleteOAuthConfig(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
