/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthAppsSuspendOAuthApp } from "../../funcs/oAuthAppsSuspendOAuthApp.js";
import { SuspendOAuthAppRequest$zodSchema } from "../../models/suspendoauthappop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SuspendOAuthAppRequest$zodSchema,
};

export const tool$oAuthAppsSuspendOAuthApp: ToolDefinition<typeof args> = {
  name: "O-auth-apps-suspend-O-auth-app",
  description: `Suspend OAuth app

Suspend an OAuth app, preventing it from authenticating or issuing tokens.
<br><br>
Existing tokens remain valid until they expire, but no new tokens can
be obtained. Use this for temporary access suspension.
<br><br>
<b>Admin Only:</b> Requires admin privileges.
<br><br>
<b>Rate Limited:</b> 10 requests per minute.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthAppsSuspendOAuthApp(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
