/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthProviderOauthRevoke } from "../../funcs/oAuthProviderOauthRevoke.js";
import { OAuthRevokeRequest$zodSchema } from "../../models/oauthrevokerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: OAuthRevokeRequest$zodSchema,
};

export const tool$oAuthProviderOauthRevoke: ToolDefinition<typeof args> = {
  name: "O-auth-provider-oauth-revoke",
  description: `Revoke an access or refresh token

OAuth 2.0 Token Revocation Endpoint (RFC 7009).
<br><br>
Revokes an access token or refresh token, preventing further use.
Revoking a refresh token also invalidates associated access tokens.
<br><br>
<b>Use Cases:</b><br>
- User logs out of third-party app<br>
- User revokes app access from account settings<br>
- Security incident response
<br><br>
<b>Note:</b> Returns 200 OK even if token was already revoked or invalid
(per RFC 7009, to prevent token enumeration).
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthProviderOauthRevoke(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
