/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthConfigurationGetOAuthConfig } from "../../funcs/oAuthConfigurationGetOAuthConfig.js";
import { GetOAuthConfigRequest$zodSchema } from "../../models/getoauthconfigop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetOAuthConfigRequest$zodSchema,
};

export const tool$oAuthConfigurationGetOAuthConfig: ToolDefinition<
  typeof args
> = {
  name: "O-auth-configuration-get-O-auth-config",
  description: `Get OAuth configuration

Get a specific OAuth configuration by ID.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthConfigurationGetOAuthConfig(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
