/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthAppsDeleteOAuthApp } from "../../funcs/oAuthAppsDeleteOAuthApp.js";
import { DeleteOAuthAppRequest$zodSchema } from "../../models/deleteoauthappop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteOAuthAppRequest$zodSchema,
};

export const tool$oAuthAppsDeleteOAuthApp: ToolDefinition<typeof args> = {
  name: "O-auth-apps-delete-O-auth-app",
  description: `Delete OAuth app

Delete (soft delete) an OAuth app.
<br><br>
This marks the app as deleted and revokes all its tokens.
The app cannot be restored after deletion.
<br><br>
<b>Admin Only:</b> Requires admin privileges.
<br><br>
<b>Rate Limited:</b> 10 requests per minute.
`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthAppsDeleteOAuthApp(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
