/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthProviderOauthAuthorize } from "../../funcs/oAuthProviderOauthAuthorize.js";
import { OauthAuthorizeRequest$zodSchema } from "../../models/oauthauthorizeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: OauthAuthorizeRequest$zodSchema,
};

export const tool$oAuthProviderOauthAuthorize: ToolDefinition<typeof args> = {
  name: "O-auth-provider-oauth-authorize",
  description: `Initiate OAuth authorization flow

OAuth 2.0 Authorization Endpoint (RFC 6749 Section 4.1.1).
<br><br>
Initiates the authorization code flow. Users are redirected here by OAuth clients
to authorize access to their account.
<br><br>
<b>Flow:</b><br>
1. Client redirects user to this endpoint with required parameters<br>
2. If not logged in, user is redirected to PipesHub login<br>
3. User sees consent page with requested scopes<br>
4. User grants or denies consent<br>
5. User is redirected back to client with authorization code
<br><br>
<b>PKCE Support (RFC 7636):</b><br>
- Required for public clients (SPA, mobile apps)<br>
- Recommended for confidential clients<br>
- Use S256 method (SHA256 hash of code_verifier)
<br><br>
<b>Security:</b><br>
- Always use HTTPS in production<br>
- State parameter provides CSRF protection<br>
- Redirect URI must match registered URIs exactly
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthProviderOauthAuthorize(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
