/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsCheckOrgExists } from "../../funcs/organizationsCheckOrgExists.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$organizationsCheckOrgExists: ToolDefinition = {
  name: "organizations-check-org-exists",
  description: `Check if organization exists

Check if any organization has been created in the system. This is typically the first API call made during initial setup.<br><br>
<b>Overview:</b><br>
This public endpoint determines whether the system has been initialized with an organization. Used by the frontend to decide whether to show the setup wizard or the login screen.<br><br>
<b>Use Cases:</b><br>
<ul>
<li>First-time setup detection</li>
<li>Onboarding flow decisions</li>
<li>System initialization checks</li>
</ul>
<b>Response:</b><br>
<ul>
<li><code>exists: true</code> - Organization exists, show login</li>
<li><code>exists: false</code> - No organization, show setup wizard</li>
</ul>
<b>Note:</b> This endpoint requires no authentication and is publicly accessible.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await organizationsCheckOrgExists(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
