/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsGetOnboardingStatus } from "../../funcs/organizationsGetOnboardingStatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$organizationsGetOnboardingStatus: ToolDefinition = {
  name: "organizations-get-onboarding-status",
  description: `Get onboarding status

Retrieve the organization's onboarding progress and status.<br><br>
<b>Response Details:</b><br>
<ul>
<li>Current onboarding step</li>
<li>Completion status of each step</li>
<li>Overall completion percentage</li>
</ul>
<b>Onboarding Steps:</b><br>
<ul>
<li>Organization profile setup</li>
<li>Admin account configuration</li>
<li>Invite team members</li>
<li>Connect integrations</li>
<li>Configure settings</li>
</ul>
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await organizationsGetOnboardingStatus(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
