/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { permissionsCreateKBPermission } from "../../funcs/permissionsCreateKBPermission.js";
import { CreateKBPermissionRequest$zodSchema } from "../../models/createkbpermissionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateKBPermissionRequest$zodSchema,
};

export const tool$permissionsCreateKBPermission: ToolDefinition<typeof args> = {
  name: "permissions-create-KB-permission",
  description: `Grant permissions

Grant access permissions to users or teams for a knowledge base.<br><br>
<b>Required Permission:</b> OWNER or ORGANIZER<br><br>
<b>Permission Roles (highest to lowest):</b><br>
<ol>
<li><b>OWNER:</b> Full control, can delete KB, manage all permissions</li>
<li><b>ORGANIZER:</b> Can manage permissions (except OWNER), edit KB settings</li>
<li><b>FILEORGANIZER:</b> Can create/delete folders, organize content</li>
<li><b>WRITER:</b> Can upload, edit, delete records</li>
<li><b>COMMENTER:</b> Can add comments (if supported)</li>
<li><b>READER:</b> View-only access</li>
</ol>
<b>Grant to Multiple:</b><br>
Provide arrays of userIds and/or teamIds to grant the same role to multiple entities.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await permissionsCreateKBPermission(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
