/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { permissionsDeleteKBPermissions } from "../../funcs/permissionsDeleteKBPermissions.js";
import { DeleteKBPermissionsRequest$zodSchema } from "../../models/deletekbpermissionsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteKBPermissionsRequest$zodSchema,
};

export const tool$permissionsDeleteKBPermissions: ToolDefinition<typeof args> =
  {
    name: "permissions-delete-KB-permissions",
    description: `Remove permissions

Remove access permissions from users or teams.<br><br>
<b>Required Permission:</b> OWNER or ORGANIZER<br><br>
<b>Note:</b> Cannot remove the last OWNER from a KB.
`,
    annotations: {
      "title": "",
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await permissionsDeleteKBPermissions(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
