/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsetOAuthGetToolsetOAuthUrl } from "../../funcs/toolsetOAuthGetToolsetOAuthUrl.js";
import { GetToolsetOAuthUrlRequest$zodSchema } from "../../models/gettoolsetoauthurlop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetToolsetOAuthUrlRequest$zodSchema,
};

export const tool$toolsetOAuthGetToolsetOAuthUrl: ToolDefinition<typeof args> =
  {
    name: "toolset-O-auth-get-toolset-O-auth-url",
    description: `Get OAuth authorization URL

Get OAuth authorization URL for a toolset.<br><br>
Returns a URL that the user should visit to authorize the toolset.
`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await toolsetOAuthGetToolsetOAuthUrl(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
