/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsetInstancesListConfiguredToolsets } from "../../funcs/toolsetInstancesListConfiguredToolsets.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$toolsetInstancesListConfiguredToolsets: ToolDefinition = {
  name: "toolset-instances-list-configured-toolsets",
  description: `List configured toolsets

Get all configured toolsets for the authenticated user
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await toolsetInstancesListConfiguredToolsets(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
