/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsetRegistryListToolsetRegistry } from "../../funcs/toolsetRegistryListToolsetRegistry.js";
import { ListToolsetRegistryRequest$zodSchema } from "../../models/listtoolsetregistryop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListToolsetRegistryRequest$zodSchema.optional(),
};

export const tool$toolsetRegistryListToolsetRegistry: ToolDefinition<
  typeof args
> = {
  name: "toolset-registry-list-toolset-registry",
  description: `List available toolsets

Get all available toolsets from the registry.<br><br>
<b>Overview:</b><br>
Returns toolsets that can be configured and used with agents.
Supports pagination and search.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await toolsetRegistryListToolsetRegistry(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
