/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsetConfigurationSaveToolsetConfig } from "../../funcs/toolsetConfigurationSaveToolsetConfig.js";
import { SaveToolsetConfigRequest$zodSchema } from "../../models/savetoolsetconfigop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SaveToolsetConfigRequest$zodSchema,
};

export const tool$toolsetConfigurationSaveToolsetConfig: ToolDefinition<
  typeof args
> = {
  name: "toolset-configuration-save-toolset-config",
  description: `Save toolset configuration

Save or update toolset configuration (deprecated - use PUT)`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await toolsetConfigurationSaveToolsetConfig(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
