/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userAccountInitAuth } from "../../funcs/userAccountInitAuth.js";
import { InitAuthRequest$zodSchema } from "../../models/initauthrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: InitAuthRequest$zodSchema,
};

export const tool$userAccountInitAuth: ToolDefinition<typeof args> = {
  name: "user-account-init-auth",
  description: `Initialize authentication session

Initialize an authentication session for a user by email address.
This is the first step in the multi-step authentication flow.
<br><br>
<b>Flow:</b><br>
1. Call this endpoint with the user's email<br>
2. Receive a session token in the <code>x-session-token</code> response header<br>
3. Use the session token in subsequent <code>/authenticate</code> calls<br>
4. The response includes <code>allowedMethods</code> for the first authentication step
<br><br>
<b>Session Token:</b><br>
- Stored in response header <code>x-session-token</code><br>
- Required for all subsequent authentication requests<br>
- Expires after a configured timeout period
<br><br>
<b>Multi-Factor Authentication:</b><br>
If the organization has MFA configured, you'll need to complete multiple
authentication steps. Each step completion returns the next step's allowed methods.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await userAccountInitAuth(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
