/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGroupsRemoveUsersFromGroup } from "../../funcs/userGroupsRemoveUsersFromGroup.js";
import { RemoveUsersFromGroupRequest$zodSchema } from "../../models/removeusersfromgroupop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RemoveUsersFromGroupRequest$zodSchema,
};

export const tool$userGroupsRemoveUsersFromGroup: ToolDefinition<typeof args> =
  {
    name: "user-groups-remove-users-from-group",
    description: `Remove users from group

Remove one or more users from a user group.<br><br>
<b>Behavior:</b><br>
<ul>
<li>Users not in the group are silently skipped</li>
<li>Operation is atomic - all specified users are removed together</li>
</ul>
<b>Restrictions:</b><br>
<ul>
<li>Cannot remove users from "everyone" group type</li>
<li>Cannot remove the last admin from admin group</li>
</ul>
`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await userGroupsRemoveUsersFromGroup(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
