/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGroupsUpdateUserGroup } from "../../funcs/userGroupsUpdateUserGroup.js";
import { UpdateUserGroupRequest$zodSchema } from "../../models/updateusergroupop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateUserGroupRequest$zodSchema,
};

export const tool$userGroupsUpdateUserGroup: ToolDefinition<typeof args> = {
  name: "user-groups-update-user-group",
  description: `Update user group

Update an existing user group's information.<br><br>
<b>Updatable Fields:</b><br>
<ul>
<li><code>name</code> - Display name (must remain unique)</li>
<li><code>description</code> - Group description</li>
</ul>
<b>Note:</b> Group type cannot be changed after creation.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await userGroupsUpdateUserGroup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
