/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userAccountGenerateLoginOtp } from "../../funcs/userAccountGenerateLoginOtp.js";
import { OtpGenerateRequest$zodSchema } from "../../models/otpgeneraterequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: OtpGenerateRequest$zodSchema,
};

export const tool$userAccountGenerateLoginOtp: ToolDefinition<typeof args> = {
  name: "user-account-generate-login-otp",
  description: `Generate and send OTP for login

Generate and send a 6-digit one-time password (OTP) to the user's email.
Use this endpoint before authenticating with the <code>otp</code> method.
<br><br>
<b>OTP Details:</b><br>
- 6 digits numeric code<br>
- Valid for <b>10 minutes</b> after generation<br>
- Sent to user's registered email address
<br><br>
<b>Rate Limiting:</b><br>
- Multiple OTP requests may be rate-limited<br>
- Wait for the current OTP to expire before requesting a new one
<br><br>
<b>CAPTCHA:</b><br>
If Cloudflare Turnstile is enabled, include <code>cf-turnstile-response</code> in the request body.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await userAccountGenerateLoginOtp(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
