/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGroupsGetUserGroupById } from "../../funcs/userGroupsGetUserGroupById.js";
import { GetUserGroupByIdRequest$zodSchema } from "../../models/getusergroupbyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetUserGroupByIdRequest$zodSchema,
};

export const tool$userGroupsGetUserGroupById: ToolDefinition<typeof args> = {
  name: "user-groups-get-user-group-by-id",
  description: `Get user group by ID

Retrieve detailed information about a specific user group.<br><br>
<b>Response Includes:</b><br>
<ul>
<li>Group metadata (name, type, description)</li>
<li>Member count</li>
<li>Creation and modification timestamps</li>
<li>Creator information</li>
</ul>
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await userGroupsGetUserGroupById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
