/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userAccountLogout } from "../../funcs/userAccountLogout.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$userAccountLogout: ToolDefinition = {
  name: "user-account-logout",
  description: `Logout current session

Log out the current user session and invalidate tokens.
<br><br>
<b>Effects:</b><br>
- Invalidates the current access token<br>
- Clears server-side session data<br>
- Client should also clear stored tokens locally
<br><br>
<b>Note:</b> This endpoint requires the access token, not the refresh token.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result] = await userAccountLogout(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
