/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGroupsDeleteUserGroup } from "../../funcs/userGroupsDeleteUserGroup.js";
import { DeleteUserGroupRequest$zodSchema } from "../../models/deleteusergroupop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteUserGroupRequest$zodSchema,
};

export const tool$userGroupsDeleteUserGroup: ToolDefinition<typeof args> = {
  name: "user-groups-delete-user-group",
  description: `Delete user group

Soft delete a user group.<br><br>
<b>Behavior:</b><br>
<ul>
<li>Group is marked as deleted (isDeleted: true)</li>
<li>Group members are not affected</li>
<li>Group can be restored by admin if needed</li>
</ul>
<b>Restrictions:</b><br>
<ul>
<li>Cannot delete system groups (admin, everyone)</li>
<li>Requires admin privileges</li>
</ul>
`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await userGroupsDeleteUserGroup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
