/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGroupsGetGroupsForUser } from "../../funcs/userGroupsGetGroupsForUser.js";
import { GetGroupsForUserRequest$zodSchema } from "../../models/getgroupsforuserop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetGroupsForUserRequest$zodSchema,
};

export const tool$userGroupsGetGroupsForUser: ToolDefinition<typeof args> = {
  name: "user-groups-get-groups-for-user",
  description: `Get groups for a user

Retrieve all user groups that a specific user belongs to.<br><br>
<b>Response Details:</b><br>
<ul>
<li>Includes all group types (admin, standard, everyone, custom)</li>
<li>Returns group metadata for each membership</li>
</ul>
<b>Use Cases:</b><br>
<ul>
<li>Displaying user's group memberships in profile</li>
<li>Access control checks</li>
<li>Permission inheritance calculations</li>
</ul>
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await userGroupsGetGroupsForUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
