/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGroupsAddUsersToGroup } from "../../funcs/userGroupsAddUsersToGroup.js";
import { AddUsersToGroupRequest$zodSchema } from "../../models/adduserstogroupop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AddUsersToGroupRequest$zodSchema,
};

export const tool$userGroupsAddUsersToGroup: ToolDefinition<typeof args> = {
  name: "user-groups-add-users-to-group",
  description: `Add users to group

Add one or more users to a user group.<br><br>
<b>Behavior:</b><br>
<ul>
<li>Users already in the group are silently skipped</li>
<li>Invalid user IDs are reported in the response</li>
<li>Operation is atomic - all valid users are added together</li>
</ul>
<b>Validation:</b><br>
<ul>
<li>All user IDs must be valid MongoDB ObjectIds</li>
<li>Users must belong to the same organization</li>
<li>Group must exist and not be deleted</li>
</ul>
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await userGroupsAddUsersToGroup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
