/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import { encodeJSON } from "../lib/encodings.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { resolveSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { CreateConnectorInstanceSecurity } from "../models/createconnectorinstanceop.js";
import {
  CreateConnectorRequest,
  CreateConnectorRequest$zodSchema,
} from "../models/createconnectorrequest.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Create connector instance
 *
 * @remarks
 * Create a new connector instance from a registry type.<br><br>
 * <b>Overview:</b><br>
 * Creates a new connector instance that can then be configured and enabled.
 * The instance is created in an unconfigured state and needs authentication
 * and filter setup before it can be activated.<br><br>
 * <b>Scope Permissions:</b><br>
 * <ul>
 * <li><code>team</code> scope requires admin privileges</li>
 * <li><code>personal</code> scope available to all users</li>
 * </ul>
 * <b>Next Steps After Creation:</b><br>
 * <ol>
 * <li>Configure authentication via <code>PUT /{id}/config/auth</code></li>
 * <li>Complete OAuth flow if needed via <code>GET /{id}/oauth/authorize</code></li>
 * <li>Set up filters via <code>POST /{id}/filters</code></li>
 * <li>Enable connector via <code>POST /{id}/toggle</code></li>
 * </ol>
 */
export function connectorInstancesCreateConnectorInstance(
  client$: SDKCore,
  security: CreateConnectorInstanceSecurity,
  request: CreateConnectorRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    Response,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    security,
    request,
    options,
  ));
}

async function $do(
  client$: SDKCore,
  security: CreateConnectorInstanceSecurity,
  request: CreateConnectorRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      Response,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => CreateConnectorRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = encodeJSON("body", payload$, { explode: true });
  const path$ = pathToFunc("/connectors")();

  const headers$ = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const requestSecurity = resolveSecurity(
    [
      {
        fieldName: "Authorization",
        type: "http:bearer",
        value: security?.bearerAuth,
      },
    ],
    [
      {
        type: "oauth2:client_credentials",
        value: {
          clientID: security?.oauth2?.clientID,
          clientSecret: security?.oauth2?.clientSecret,
        },
      },
    ],
  );

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "createConnectorInstance",
    oAuth2Scopes: ["connector:write"],
    resolvedSecurity: requestSecurity,
    securitySource: security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  return [doResult, {
    status: "complete",
    "request": req$,
    response: doResult.value,
  }];
}
