/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { resolveSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  ListKnowledgeBasesRequest,
  ListKnowledgeBasesRequest$zodSchema,
  ListKnowledgeBasesSecurity,
} from "../models/listknowledgebasesop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * List all knowledge bases
 *
 * @remarks
 * Retrieve a paginated list of all knowledge bases accessible to the authenticated user.<br><br>
 * <b>Overview:</b><br>
 * Returns knowledge bases where the user has at least READER permission. Results include the user's role for each KB.<br><br>
 * <b>Filtering:</b><br>
 * <ul>
 * <li><b>search:</b> Full-text search on KB names (max 1000 chars)</li>
 * <li><b>permissions:</b> Filter by user's role (comma-separated: OWNER,WRITER,READER)</li>
 * </ul>
 * <b>Sorting Options:</b><br>
 * <ul>
 * <li><code>name</code> - Alphabetical by KB name</li>
 * <li><code>createdAtTimestamp</code> - By creation date</li>
 * <li><code>updatedAtTimestamp</code> - By last modification</li>
 * <li><code>userRole</code> - By permission level</li>
 * </ul>
 * <b>Performance:</b><br>
 * Uses efficient pagination with limit/offset. For large result sets, use smaller page sizes.
 */
export function knowledgeBasesListKnowledgeBases(
  client$: SDKCore,
  security: ListKnowledgeBasesSecurity,
  request?: ListKnowledgeBasesRequest | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    Response,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    security,
    request,
    options,
  ));
}

async function $do(
  client$: SDKCore,
  security: ListKnowledgeBasesSecurity,
  request?: ListKnowledgeBasesRequest | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      Response,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => ListKnowledgeBasesRequest$zodSchema.optional().parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;
  const path$ = pathToFunc("/knowledgeBase")();
  const query$ = encodeFormQuery({
    "limit": payload$?.limit,
    "page": payload$?.page,
    "permissions": payload$?.permissions,
    "search": payload$?.search,
    "sortBy": payload$?.sortBy,
    "sortOrder": payload$?.sortOrder,
  });

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
  }));

  const requestSecurity = resolveSecurity(
    [
      {
        fieldName: "Authorization",
        type: "http:bearer",
        value: security?.bearerAuth,
      },
    ],
    [
      {
        type: "oauth2:client_credentials",
        value: {
          clientID: security?.oauth2?.clientID,
          clientSecret: security?.oauth2?.clientSecret,
        },
      },
    ],
  );

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "listKnowledgeBases",
    oAuth2Scopes: ["kb:read"],
    resolvedSecurity: requestSecurity,
    securitySource: security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  return [doResult, {
    status: "complete",
    "request": req$,
    response: doResult.value,
  }];
}
