/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { resolveSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  DeleteOrganizationRequest,
  DeleteOrganizationRequest$zodSchema,
  DeleteOrganizationSecurity,
} from "../models/deleteorganizationop.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Delete organization
 *
 * @remarks
 * Permanently delete an organization and all associated data.<br><br>
 * <b>WARNING:</b> This action is <b>irreversible</b>.<br><br>
 * <b>Data Deleted:</b><br>
 * <ul>
 * <li>All user accounts in the organization</li>
 * <li>All teams and user groups</li>
 * <li>All documents and storage data</li>
 * <li>All configuration and settings</li>
 * </ul>
 * <b>Requirements:</b><br>
 * <ul>
 * <li>Must be the organization owner (super admin)</li>
 * <li>Must provide confirmation parameter</li>
 * <li>All active subscriptions must be cancelled first</li>
 * </ul>
 */
export function organizationsDeleteOrganization(
  client$: SDKCore,
  security: DeleteOrganizationSecurity,
  request: DeleteOrganizationRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    Response,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    security,
    request,
    options,
  ));
}

async function $do(
  client$: SDKCore,
  security: DeleteOrganizationSecurity,
  request: DeleteOrganizationRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      Response,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => DeleteOrganizationRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = null;
  const path$ = pathToFunc("/org")();
  const query$ = encodeFormQuery({
    "confirm": payload$.confirm,
  });

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
  }));

  const requestSecurity = resolveSecurity(
    [
      {
        fieldName: "Authorization",
        type: "http:bearer",
        value: security?.bearerAuth,
      },
    ],
    [
      {
        type: "oauth2:client_credentials",
        value: {
          clientID: security?.oauth2?.clientID,
          clientSecret: security?.oauth2?.clientSecret,
        },
      },
    ],
  );

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "deleteOrganization",
    oAuth2Scopes: ["org:admin"],
    resolvedSecurity: requestSecurity,
    securitySource: security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "DELETE",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  return [doResult, {
    status: "complete",
    "request": req$,
    response: doResult.value,
  }];
}
