/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import { appendForm, encodeSimple } from "../lib/encodings.js";
import {
  getContentTypeFromFileName,
  readableStreamToArrayBuffer,
} from "../lib/files.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { resolveSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  UploadRecordsToFolderRequest,
  UploadRecordsToFolderRequest$zodSchema,
  UploadRecordsToFolderSecurity,
} from "../models/uploadrecordstofolderop.js";
import { APICall, APIPromise } from "../types/async.js";
import { isBlobLike } from "../types/blobs.js";
import { Result } from "../types/fp.js";
import { isReadableStream } from "../types/streams.js";

/**
 * Upload files to folder
 *
 * @remarks
 * Upload files directly to a specific folder within a knowledge base.<br><br>
 * <b>Same as KB upload</b> but files are placed in the specified folder instead of KB root.
 */
export function uploadUploadRecordsToFolder(
  client$: SDKCore,
  security: UploadRecordsToFolderSecurity,
  request: UploadRecordsToFolderRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    Response,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    security,
    request,
    options,
  ));
}

async function $do(
  client$: SDKCore,
  security: UploadRecordsToFolderSecurity,
  request: UploadRecordsToFolderRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      Response,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => UploadRecordsToFolderRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = new FormData();
  for (const fileItem of payload$.body.files ?? []) {
    if (isBlobLike(fileItem)) {
      appendForm(body$, "files", fileItem);
    } else if (isReadableStream(fileItem.content)) {
      const buffer = await readableStreamToArrayBuffer(fileItem.content);
      const contentType = getContentTypeFromFileName(fileItem.fileName)
        || "application/octet-stream";
      const blob = new Blob([buffer], { type: contentType });
      appendForm(body$, "files", blob, fileItem.fileName);
    } else {
      const contentType = getContentTypeFromFileName(fileItem.fileName)
        || "application/octet-stream";
      appendForm(
        body$,
        "files",
        new Blob([fileItem.content], { type: contentType }),
        fileItem.fileName,
      );
    }
  }
  if (payload$.body.files_metadata !== undefined) {
    appendForm(body$, "files_metadata", payload$.body.files_metadata);
  }
  if (payload$.body.isVersioned !== undefined) {
    appendForm(body$, "isVersioned", payload$.body.isVersioned);
  }

  const pathParams$ = {
    folderId: encodeSimple("folderId", payload$.folderId, {
      explode: false,
      charEncoding: "percent",
    }),
    kbId: encodeSimple("kbId", payload$.kbId, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc("/knowledgeBase/{kbId}/folder/{folderId}/upload")(
    pathParams$,
  );

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
  }));

  const requestSecurity = resolveSecurity(
    [
      {
        fieldName: "Authorization",
        type: "http:bearer",
        value: security?.bearerAuth,
      },
    ],
    [
      {
        type: "oauth2:client_credentials",
        value: {
          clientID: security?.oauth2?.clientID,
          clientSecret: security?.oauth2?.clientSecret,
        },
      },
    ],
  );

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "uploadRecordsToFolder",
    oAuth2Scopes: ["kb:upload"],
    resolvedSecurity: requestSecurity,
    securitySource: security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  return [doResult, {
    status: "complete",
    "request": req$,
    response: doResult.value,
  }];
}
