/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SDKCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool, registerDynamicTools } from "./tools.js";
import { tool$agentTemplatesCreateAgentTemplate } from "./tools/agentTemplatesCreateAgentTemplate.js";
import { tool$aiModelsProvidersDeleteAIModelProvider } from "./tools/aiModelsProvidersDeleteAIModelProvider.js";
import { tool$connectorFiltersSaveConnectorFilters } from "./tools/connectorFiltersSaveConnectorFilters.js";
import { tool$connectorOAuthHandleOAuthCallback } from "./tools/connectorOAuthHandleOAuthCallback.js";
import { tool$conversationsAddMessage } from "./tools/conversationsAddMessage.js";
import { tool$oAuthAppsActivateOAuthApp } from "./tools/oAuthAppsActivateOAuthApp.js";
import { tool$oAuthAppsCreateOAuthApp } from "./tools/oAuthAppsCreateOAuthApp.js";
import { tool$oAuthAppsDeleteOAuthApp } from "./tools/oAuthAppsDeleteOAuthApp.js";
import { tool$oAuthAppsGetOAuthApp } from "./tools/oAuthAppsGetOAuthApp.js";
import { tool$oAuthAppsListOAuthApps } from "./tools/oAuthAppsListOAuthApps.js";
import { tool$oAuthAppsListOAuthAppTokens } from "./tools/oAuthAppsListOAuthAppTokens.js";
import { tool$oAuthAppsListOAuthScopes } from "./tools/oAuthAppsListOAuthScopes.js";
import { tool$oAuthAppsRegenerateOAuthAppSecret } from "./tools/oAuthAppsRegenerateOAuthAppSecret.js";
import { tool$oAuthAppsRevokeAllOAuthAppTokens } from "./tools/oAuthAppsRevokeAllOAuthAppTokens.js";
import { tool$oAuthAppsSuspendOAuthApp } from "./tools/oAuthAppsSuspendOAuthApp.js";
import { tool$oAuthAppsUpdateOAuthApp } from "./tools/oAuthAppsUpdateOAuthApp.js";
import { tool$oAuthConfigurationCreateOAuthConfig } from "./tools/oAuthConfigurationCreateOAuthConfig.js";
import { tool$oAuthConfigurationDeleteOAuthConfig } from "./tools/oAuthConfigurationDeleteOAuthConfig.js";
import { tool$oAuthConfigurationGetOAuthConfig } from "./tools/oAuthConfigurationGetOAuthConfig.js";
import { tool$oAuthConfigurationGetOAuthConnectorType } from "./tools/oAuthConfigurationGetOAuthConnectorType.js";
import { tool$oAuthConfigurationGetOAuthRegistry } from "./tools/oAuthConfigurationGetOAuthRegistry.js";
import { tool$oAuthConfigurationListOAuthConfigs } from "./tools/oAuthConfigurationListOAuthConfigs.js";
import { tool$oAuthConfigurationListOAuthConfigsByType } from "./tools/oAuthConfigurationListOAuthConfigsByType.js";
import { tool$oAuthConfigurationUpdateOAuthConfig } from "./tools/oAuthConfigurationUpdateOAuthConfig.js";
import { tool$oAuthExchangeOAuthCode } from "./tools/oAuthExchangeOAuthCode.js";
import { tool$oAuthProviderOauthAuthorize } from "./tools/oAuthProviderOauthAuthorize.js";
import { tool$oAuthProviderOauthAuthorizeConsent } from "./tools/oAuthProviderOauthAuthorizeConsent.js";
import { tool$oAuthProviderOauthIntrospect } from "./tools/oAuthProviderOauthIntrospect.js";
import { tool$oAuthProviderOauthRevoke } from "./tools/oAuthProviderOauthRevoke.js";
import { tool$oAuthProviderOauthToken } from "./tools/oAuthProviderOauthToken.js";
import { tool$openIDConnectJwks } from "./tools/openIDConnectJwks.js";
import { tool$openIDConnectOauthUserInfo } from "./tools/openIDConnectOauthUserInfo.js";
import { tool$openIDConnectOpenidConfiguration } from "./tools/openIDConnectOpenidConfiguration.js";
import { tool$organizationAuthConfigGetAuthMethods } from "./tools/organizationAuthConfigGetAuthMethods.js";
import { tool$organizationAuthConfigUpdateAuthMethod } from "./tools/organizationAuthConfigUpdateAuthMethod.js";
import { tool$organizationsCheckOrgExists } from "./tools/organizationsCheckOrgExists.js";
import { tool$organizationsCreateOrganization } from "./tools/organizationsCreateOrganization.js";
import { tool$organizationsGetOnboardingStatus } from "./tools/organizationsGetOnboardingStatus.js";
import { tool$organizationsUpdateOnboardingStatus } from "./tools/organizationsUpdateOnboardingStatus.js";
import { tool$permissionsCreateKBPermission } from "./tools/permissionsCreateKBPermission.js";
import { tool$permissionsDeleteKBPermissions } from "./tools/permissionsDeleteKBPermissions.js";
import { tool$recordsUpdateRecord } from "./tools/recordsUpdateRecord.js";
import { tool$samlSignInViaSAML } from "./tools/samlSignInViaSAML.js";
import { tool$toolsetConfigurationDeleteToolsetConfig } from "./tools/toolsetConfigurationDeleteToolsetConfig.js";
import { tool$toolsetConfigurationGetToolsetConfig } from "./tools/toolsetConfigurationGetToolsetConfig.js";
import { tool$toolsetConfigurationSaveToolsetConfig } from "./tools/toolsetConfigurationSaveToolsetConfig.js";
import { tool$toolsetConfigurationUpdateToolsetConfig } from "./tools/toolsetConfigurationUpdateToolsetConfig.js";
import { tool$toolsetInstancesCheckToolsetStatus } from "./tools/toolsetInstancesCheckToolsetStatus.js";
import { tool$toolsetInstancesCreateToolset } from "./tools/toolsetInstancesCreateToolset.js";
import { tool$toolsetInstancesListConfiguredToolsets } from "./tools/toolsetInstancesListConfiguredToolsets.js";
import { tool$toolsetOAuthGetToolsetOAuthUrl } from "./tools/toolsetOAuthGetToolsetOAuthUrl.js";
import { tool$toolsetOAuthHandleToolsetOAuthCallback } from "./tools/toolsetOAuthHandleToolsetOAuthCallback.js";
import { tool$toolsetRegistryGetToolsetSchema } from "./tools/toolsetRegistryGetToolsetSchema.js";
import { tool$toolsetRegistryListToolsetRegistry } from "./tools/toolsetRegistryListToolsetRegistry.js";
import { tool$userAccountAuthenticate } from "./tools/userAccountAuthenticate.js";
import { tool$userAccountForgotPassword } from "./tools/userAccountForgotPassword.js";
import { tool$userAccountGenerateLoginOtp } from "./tools/userAccountGenerateLoginOtp.js";
import { tool$userAccountInitAuth } from "./tools/userAccountInitAuth.js";
import { tool$userAccountLogout } from "./tools/userAccountLogout.js";
import { tool$userGroupsAddUsersToGroup } from "./tools/userGroupsAddUsersToGroup.js";
import { tool$userGroupsCreateUserGroup } from "./tools/userGroupsCreateUserGroup.js";
import { tool$userGroupsDeleteUserGroup } from "./tools/userGroupsDeleteUserGroup.js";
import { tool$userGroupsGetAllUserGroups } from "./tools/userGroupsGetAllUserGroups.js";
import { tool$userGroupsGetGroupsForUser } from "./tools/userGroupsGetGroupsForUser.js";
import { tool$userGroupsGetUserGroupById } from "./tools/userGroupsGetUserGroupById.js";
import { tool$userGroupsRemoveUsersFromGroup } from "./tools/userGroupsRemoveUsersFromGroup.js";
import { tool$userGroupsUpdateUserGroup } from "./tools/userGroupsUpdateUserGroup.js";
import { tool$usersCreateUser } from "./tools/usersCreateUser.js";
import { tool$usersGetUserDisplayPicture } from "./tools/usersGetUserDisplayPicture.js";
import { tool$usersGetUserEmailById } from "./tools/usersGetUserEmailById.js";
import { tool$usersRemoveUserDisplayPicture } from "./tools/usersRemoveUserDisplayPicture.js";
import { tool$usersResendUserInvite } from "./tools/usersResendUserInvite.js";
import { tool$usersUnblockUser } from "./tools/usersUnblockUser.js";
import { tool$usersUploadUserDisplayPicture } from "./tools/usersUploadUserDisplayPicture.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => SDKCore;
  serverURL: string;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "SDK",
    version: "0.0.1",
  });

  const getClient = deps.getSDK || (() =>
    new SDKCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$userAccountInitAuth);
  tool(tool$userAccountAuthenticate);
  tool(tool$userAccountGenerateLoginOtp);
  tool(tool$userAccountForgotPassword);
  tool(tool$userAccountLogout);
  tool(tool$oAuthExchangeOAuthCode);
  tool(tool$oAuthProviderOauthAuthorize);
  tool(tool$oAuthProviderOauthAuthorizeConsent);
  tool(tool$oAuthProviderOauthToken);
  tool(tool$oAuthProviderOauthRevoke);
  tool(tool$oAuthProviderOauthIntrospect);
  tool(tool$openIDConnectOauthUserInfo);
  tool(tool$openIDConnectOpenidConfiguration);
  tool(tool$openIDConnectJwks);
  tool(tool$oAuthAppsListOAuthApps);
  tool(tool$oAuthAppsCreateOAuthApp);
  tool(tool$oAuthAppsListOAuthScopes);
  tool(tool$oAuthAppsGetOAuthApp);
  tool(tool$oAuthAppsUpdateOAuthApp);
  tool(tool$oAuthAppsDeleteOAuthApp);
  tool(tool$oAuthAppsRegenerateOAuthAppSecret);
  tool(tool$oAuthAppsSuspendOAuthApp);
  tool(tool$oAuthAppsActivateOAuthApp);
  tool(tool$oAuthAppsListOAuthAppTokens);
  tool(tool$oAuthAppsRevokeAllOAuthAppTokens);
  tool(tool$organizationAuthConfigGetAuthMethods);
  tool(tool$organizationAuthConfigUpdateAuthMethod);
  tool(tool$samlSignInViaSAML);
  tool(tool$usersCreateUser);
  tool(tool$usersGetUserEmailById);
  tool(tool$usersUploadUserDisplayPicture);
  tool(tool$usersGetUserDisplayPicture);
  tool(tool$usersRemoveUserDisplayPicture);
  tool(tool$usersResendUserInvite);
  tool(tool$usersUnblockUser);
  tool(tool$organizationsCheckOrgExists);
  tool(tool$organizationsCreateOrganization);
  tool(tool$organizationsGetOnboardingStatus);
  tool(tool$organizationsUpdateOnboardingStatus);
  tool(tool$userGroupsCreateUserGroup);
  tool(tool$userGroupsGetAllUserGroups);
  tool(tool$userGroupsGetUserGroupById);
  tool(tool$userGroupsUpdateUserGroup);
  tool(tool$userGroupsDeleteUserGroup);
  tool(tool$userGroupsAddUsersToGroup);
  tool(tool$userGroupsRemoveUsersFromGroup);
  tool(tool$userGroupsGetGroupsForUser);
  tool(tool$recordsUpdateRecord);
  tool(tool$permissionsCreateKBPermission);
  tool(tool$permissionsDeleteKBPermissions);
  tool(tool$conversationsAddMessage);
  tool(tool$agentTemplatesCreateAgentTemplate);
  tool(tool$connectorOAuthHandleOAuthCallback);
  tool(tool$connectorFiltersSaveConnectorFilters);
  tool(tool$toolsetRegistryListToolsetRegistry);
  tool(tool$toolsetRegistryGetToolsetSchema);
  tool(tool$toolsetInstancesCreateToolset);
  tool(tool$toolsetInstancesListConfiguredToolsets);
  tool(tool$toolsetInstancesCheckToolsetStatus);
  tool(tool$toolsetConfigurationGetToolsetConfig);
  tool(tool$toolsetConfigurationSaveToolsetConfig);
  tool(tool$toolsetConfigurationUpdateToolsetConfig);
  tool(tool$toolsetConfigurationDeleteToolsetConfig);
  tool(tool$toolsetOAuthGetToolsetOAuthUrl);
  tool(tool$toolsetOAuthHandleToolsetOAuthCallback);
  tool(tool$oAuthConfigurationGetOAuthRegistry);
  tool(tool$oAuthConfigurationGetOAuthConnectorType);
  tool(tool$oAuthConfigurationListOAuthConfigs);
  tool(tool$oAuthConfigurationListOAuthConfigsByType);
  tool(tool$oAuthConfigurationCreateOAuthConfig);
  tool(tool$oAuthConfigurationGetOAuthConfig);
  tool(tool$oAuthConfigurationUpdateOAuthConfig);
  tool(tool$oAuthConfigurationDeleteOAuthConfig);
  tool(tool$aiModelsProvidersDeleteAIModelProvider);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
