workflowVersion: 1.0.0
speakeasyVersion: 1.731.2
sources:
    PipesHub API:
        inputs:
            - location: source_specs/pipeshub-sdk-openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/pipeshub/test/pipes-hub-api
targets:
    go:
        target: go
        source: PipesHub API
        output: ./pipeshub-sdk-go
        testing:
          enabled: false
          mockServer:
            enabled: false
    python:
        target: python
        source: PipesHub API
        output: ./pipeshub-sdk-python
        testing:
          enabled: false
          mockServer:
            enabled: false
    typescript:
        target: typescript
        source: PipesHub API
        output: ./pipeshub-sdk-typescript
        testing:
          enabled: false
          mockServer:
            enabled: false
