/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ActivateOAuthAppRequest = { appId: string };

export const ActivateOAuthAppRequest$zodSchema: z.ZodType<
  ActivateOAuthAppRequest
> = z.object({
  appId: z.string().describe("OAuth app ID"),
});
