/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Filters, Filters$zodSchema } from "./filters.js";

/**
 * Request body for adding a message to an existing conversation
 */
export type AddMessageRequest = {
  query: string;
  filters?: Filters | undefined;
  modelKey?: string | undefined;
  modelName?: string | undefined;
  chatMode?: string | undefined;
};

export const AddMessageRequest$zodSchema: z.ZodType<AddMessageRequest> = z
  .object({
    chatMode: z.string().optional(),
    filters: Filters$zodSchema.optional(),
    modelKey: z.string().optional(),
    modelName: z.string().optional(),
    query: z.string(),
  }).describe("Request body for adding a message to an existing conversation");
