/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * JSON Schema for tool inputs
 */
export type InputSchema = {};

export const InputSchema$zodSchema: z.ZodType<InputSchema> = z.object({})
  .describe("JSON Schema for tool inputs");

/**
 * A tool that agents can use to perform actions
 */
export type AgentTool = {
  key?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  inputSchema?: InputSchema | undefined;
  isEnabled?: boolean | undefined;
};

export const AgentTool$zodSchema: z.ZodType<AgentTool> = z.object({
  description: z.string().optional(),
  inputSchema: z.lazy(() => InputSchema$zodSchema).optional(),
  isEnabled: z.boolean().optional(),
  key: z.string().optional(),
  name: z.string().optional(),
}).describe("A tool that agents can use to perform actions");
