/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AIModelProviderConfigConfiguration = {
  model?: string | undefined;
  apiKey?: string | undefined;
  endpoint?: string | undefined;
};

export const AIModelProviderConfigConfiguration$zodSchema: z.ZodType<
  AIModelProviderConfigConfiguration
> = z.object({
  apiKey: z.string().optional(),
  endpoint: z.string().optional(),
  model: z.string().optional(),
});

export type AIModelProviderConfig = {
  provider: string;
  configuration: AIModelProviderConfigConfiguration;
  isMultimodal?: boolean | undefined;
  isReasoning?: boolean | undefined;
  isDefault?: boolean | undefined;
  contextLength?: number | null | undefined;
  modelKey?: string | undefined;
};

export const AIModelProviderConfig$zodSchema: z.ZodType<AIModelProviderConfig> =
  z.object({
    configuration: z.lazy(() => AIModelProviderConfigConfiguration$zodSchema),
    contextLength: z.int().nullable().optional(),
    isDefault: z.boolean().default(false),
    isMultimodal: z.boolean().default(false),
    isReasoning: z.boolean().default(false),
    modelKey: z.string().optional(),
    provider: z.string(),
  });
