/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  AIModelProviderConfig,
  AIModelProviderConfig$zodSchema,
} from "./aimodelproviderconfig.js";

export const AIModelProviderResponseStatus = {
  Success: "success",
  Error: "error",
} as const;
export type AIModelProviderResponseStatus = ClosedEnum<
  typeof AIModelProviderResponseStatus
>;

export const AIModelProviderResponseStatus$zodSchema = z.enum([
  "success",
  "error",
]);

/**
 * Response containing AI model provider details
 */
export type AIModelProviderResponse = {
  status?: AIModelProviderResponseStatus | undefined;
  message?: string | undefined;
  data?: AIModelProviderConfig | undefined;
};

export const AIModelProviderResponse$zodSchema: z.ZodType<
  AIModelProviderResponse
> = z.object({
  data: AIModelProviderConfig$zodSchema.optional(),
  message: z.string().optional(),
  status: AIModelProviderResponseStatus$zodSchema.optional(),
}).describe("Response containing AI model provider details");
