/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Supported application/connector types
 */
export const AppType = {
  Drive: "drive",
  Gmail: "gmail",
  Onedrive: "onedrive",
  SharepointOnline: "sharepointOnline",
  Bookstack: "bookstack",
  Confluence: "confluence",
  Jira: "jira",
  Slack: "slack",
  Dropbox: "dropbox",
  Outlook: "outlook",
  Servicenow: "servicenow",
  Web: "web",
  Local: "local",
} as const;
/**
 * Supported application/connector types
 */
export type AppType = ClosedEnum<typeof AppType>;

export const AppType$zodSchema = z.enum([
  "drive",
  "gmail",
  "onedrive",
  "sharepointOnline",
  "bookstack",
  "confluence",
  "jira",
  "slack",
  "dropbox",
  "outlook",
  "servicenow",
  "web",
  "local",
]).describe("Supported application/connector types");
