/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of authentication method:
 *
 * @remarks
 * - `password`: Email/password authentication
 * - `otp`: One-time password via email (6-digit, expires in 10 minutes)
 * - `google`: Google OAuth 2.0
 * - `microsoft`: Microsoft OAuth 2.0
 * - `azureAd`: Azure Active Directory
 * - `samlSso`: SAML 2.0 Single Sign-On
 * - `oauth`: Generic OAuth 2.0 provider
 */
export const AuthMethodType = {
  SamlSso: "samlSso",
  Otp: "otp",
  Password: "password",
  Google: "google",
  Microsoft: "microsoft",
  AzureAd: "azureAd",
  Oauth: "oauth",
} as const;
/**
 * Type of authentication method:
 *
 * @remarks
 * - `password`: Email/password authentication
 * - `otp`: One-time password via email (6-digit, expires in 10 minutes)
 * - `google`: Google OAuth 2.0
 * - `microsoft`: Microsoft OAuth 2.0
 * - `azureAd`: Azure Active Directory
 * - `samlSso`: SAML 2.0 Single Sign-On
 * - `oauth`: Generic OAuth 2.0 provider
 */
export type AuthMethodType = ClosedEnum<typeof AuthMethodType>;

export const AuthMethodType$zodSchema = z.enum([
  "samlSso",
  "otp",
  "password",
  "google",
  "microsoft",
  "azureAd",
  "oauth",
]).describe(
  "Type of authentication method:\n- `password`: Email/password authentication\n- `otp`: One-time password via email (6-digit, expires in 10 minutes)\n- `google`: Google OAuth 2.0\n- `microsoft`: Microsoft OAuth 2.0\n- `azureAd`: Azure Active Directory\n- `samlSso`: SAML 2.0 Single Sign-On\n- `oauth`: Generic OAuth 2.0 provider\n",
);

/**
 * Authentication method configuration
 */
export type AuthMethod = { type: AuthMethodType };

export const AuthMethod$zodSchema: z.ZodType<AuthMethod> = z.object({
  type: AuthMethodType$zodSchema,
}).describe("Authentication method configuration");
