/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthMethod, AuthMethod$zodSchema } from "./authmethod.js";

/**
 * A single step in multi-factor authentication flow
 */
export type AuthStep = { order: number; allowedMethods: Array<AuthMethod> };

export const AuthStep$zodSchema: z.ZodType<AuthStep> = z.object({
  allowedMethods: z.array(AuthMethod$zodSchema),
  order: z.int(),
}).describe("A single step in multi-factor authentication flow");
