/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Authentication error response with details for debugging and user feedback.<br><br>
 *
 * @remarks
 * <b>Common Error Codes:</b><br>
 * <ul>
 * <li><code>INVALID_CREDENTIALS</code> - Wrong password or OTP</li>
 * <li><code>ACCOUNT_BLOCKED</code> - Account locked after 5 failed attempts</li>
 * <li><code>SESSION_EXPIRED</code> - Session token has expired</li>
 * <li><code>OTP_EXPIRED</code> - OTP code has expired (10 min validity)</li>
 * <li><code>USER_NOT_FOUND</code> - Email not registered</li>
 * <li><code>INVALID_TOKEN</code> - JWT token is invalid or malformed</li>
 * <li><code>METHOD_NOT_ALLOWED</code> - Auth method not enabled for org</li>
 * </ul>
 */
export type AuthError = {
  error?: string | undefined;
  message?: string | undefined;
  code?: string | undefined;
  statusCode?: number | undefined;
};

export const AuthError$zodSchema: z.ZodType<AuthError> = z.object({
  code: z.string().optional(),
  error: z.string().optional(),
  message: z.string().optional(),
  statusCode: z.int().optional(),
}).describe(
  "Authentication error response with details for debugging and user feedback.<br><br>\n<b>Common Error Codes:</b><br>\n<ul>\n<li><code>INVALID_CREDENTIALS</code> - Wrong password or OTP</li>\n<li><code>ACCOUNT_BLOCKED</code> - Account locked after 5 failed attempts</li>\n<li><code>SESSION_EXPIRED</code> - Session token has expired</li>\n<li><code>OTP_EXPIRED</code> - OTP code has expired (10 min validity)</li>\n<li><code>USER_NOT_FOUND</code> - Email not registered</li>\n<li><code>INVALID_TOKEN</code> - JWT token is invalid or malformed</li>\n<li><code>METHOD_NOT_ALLOWED</code> - Auth method not enabled for org</li>\n</ul>\n",
);
