/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthProviders, AuthProviders$zodSchema } from "./authproviders.js";

/**
 * Authentication step status (for multi-step auth)
 */
export const AuthenticateResponseStatus = {
  Success: "success",
} as const;
/**
 * Authentication step status (for multi-step auth)
 */
export type AuthenticateResponseStatus = ClosedEnum<
  typeof AuthenticateResponseStatus
>;

export const AuthenticateResponseStatus$zodSchema = z.enum([
  "success",
]).describe("Authentication step status (for multi-step auth)");

export const AuthenticateResponseAllowedMethod = {
  SamlSso: "samlSso",
  Otp: "otp",
  Password: "password",
  Google: "google",
  Microsoft: "microsoft",
  AzureAd: "azureAd",
  Oauth: "oauth",
} as const;
export type AuthenticateResponseAllowedMethod = ClosedEnum<
  typeof AuthenticateResponseAllowedMethod
>;

export const AuthenticateResponseAllowedMethod$zodSchema = z.enum([
  "samlSso",
  "otp",
  "password",
  "google",
  "microsoft",
  "azureAd",
  "oauth",
]);

/**
 * Authentication response. Two possible outcomes:
 *
 * @remarks
 * 1. **Multi-step in progress**: Returns `status: "success"` with `nextStep` and `allowedMethods`
 * 2. **Fully authenticated**: Returns `message: "Fully authenticated"` with `accessToken` and `refreshToken`
 */
export type AuthenticateResponse = {
  status?: AuthenticateResponseStatus | undefined;
  message?: string | undefined;
  nextStep?: number | undefined;
  allowedMethods?: Array<AuthenticateResponseAllowedMethod> | undefined;
  authProviders?: AuthProviders | undefined;
  accessToken?: string | undefined;
  refreshToken?: string | undefined;
};

export const AuthenticateResponse$zodSchema: z.ZodType<AuthenticateResponse> = z
  .object({
    accessToken: z.string().optional(),
    allowedMethods: z.array(AuthenticateResponseAllowedMethod$zodSchema)
      .optional(),
    authProviders: AuthProviders$zodSchema.optional(),
    message: z.string().optional(),
    nextStep: z.int().optional(),
    refreshToken: z.string().optional(),
    status: AuthenticateResponseStatus$zodSchema.optional(),
  }).describe(
    "Authentication response. Two possible outcomes:\n1. **Multi-step in progress**: Returns `status: \"success\"` with `nextStep` and `allowedMethods`\n2. **Fully authenticated**: Returns `message: \"Fully authenticated\"` with `accessToken` and `refreshToken`\n",
  );
