/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  OAuthCredentials,
  OAuthCredentials$zodSchema,
} from "./oauthcredentials.js";
import { OtpCredentials, OtpCredentials$zodSchema } from "./otpcredentials.js";
import {
  PasswordCredentials,
  PasswordCredentials$zodSchema,
} from "./passwordcredentials.js";

/**
 * Authentication method to use
 */
export const Method = {
  SamlSso: "samlSso",
  Otp: "otp",
  Password: "password",
  Google: "google",
  Microsoft: "microsoft",
  AzureAd: "azureAd",
  Oauth: "oauth",
} as const;
/**
 * Authentication method to use
 */
export type Method = ClosedEnum<typeof Method>;

export const Method$zodSchema = z.enum([
  "samlSso",
  "otp",
  "password",
  "google",
  "microsoft",
  "azureAd",
  "oauth",
]).describe("Authentication method to use");

/**
 * Credentials based on the authentication method
 */
export type Credentials =
  | PasswordCredentials
  | OtpCredentials
  | OAuthCredentials
  | string;

export const Credentials$zodSchema: z.ZodType<Credentials> = z.union([
  PasswordCredentials$zodSchema,
  OtpCredentials$zodSchema,
  OAuthCredentials$zodSchema,
  z.string(),
]).describe("Credentials based on the authentication method");

/**
 * Request to authenticate using specified method.
 *
 * @remarks
 * **Credential format varies by method:**
 * - `password`: `{ password: "string" }`
 * - `otp`: `{ otp: "123456" }` (6-digit code)
 * - `google`: `"google-id-token-string"`
 * - `microsoft`: `{ accessToken: "...", idToken: "..." }`
 * - `azureAd`: `{ accessToken: "...", idToken: "..." }`
 * - `oauth`: `{ accessToken: "...", idToken: "..." }`
 * - `samlSso`: handled via redirect flow
 */
export type AuthenticateRequest = {
  method: Method;
  credentials: PasswordCredentials | OtpCredentials | OAuthCredentials | string;
  email?: string | undefined;
  cfTurnstileResponse?: string | undefined;
};

export const AuthenticateRequest$zodSchema: z.ZodType<AuthenticateRequest> = z
  .object({
    cfTurnstileResponse: z.string().optional(),
    credentials: z.union([
      PasswordCredentials$zodSchema,
      OtpCredentials$zodSchema,
      OAuthCredentials$zodSchema,
      z.string(),
    ]),
    email: z.string().optional(),
    method: Method$zodSchema,
  }).describe(
    "Request to authenticate using specified method.\n**Credential format varies by method:**\n- `password`: `{ password: \"string\" }`\n- `otp`: `{ otp: \"123456\" }` (6-digit code)\n- `google`: `\"google-id-token-string\"`\n- `microsoft`: `{ accessToken: \"...\", idToken: \"...\" }`\n- `azureAd`: `{ accessToken: \"...\", idToken: \"...\" }`\n- `oauth`: `{ accessToken: \"...\", idToken: \"...\" }`\n- `samlSso`: handled via redirect flow\n",
  );
