/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type BulkInviteUsersSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const BulkInviteUsersSecurity$zodSchema: z.ZodType<
  BulkInviteUsersSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

/**
 * Request payload
 */
export type BulkInviteUsersRequest = {
  emails: Array<string>;
  groupIds?: Array<string> | undefined;
  sendEmail?: boolean | undefined;
};

export const BulkInviteUsersRequest$zodSchema: z.ZodType<
  BulkInviteUsersRequest
> = z.object({
  emails: z.array(z.string()),
  groupIds: z.array(z.string()).optional(),
  sendEmail: z.boolean().default(true),
}).describe("Request payload");

export type Failure = {
  email?: string | undefined;
  reason?: string | undefined;
};

export const Failure$zodSchema: z.ZodType<Failure> = z.object({
  email: z.string().optional(),
  reason: z.string().optional(),
});

/**
 * Bulk invitation processed
 */
export type BulkInviteUsersResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  invited?: number | undefined;
  skipped?: number | undefined;
  failed?: number | undefined;
  failures?: Array<Failure> | undefined;
};

export const BulkInviteUsersResponse$zodSchema: z.ZodType<
  BulkInviteUsersResponse
> = z.object({
  failed: z.int().optional(),
  failures: z.array(z.lazy(() => Failure$zodSchema)).optional(),
  invited: z.int().optional(),
  message: z.string().optional(),
  skipped: z.int().optional(),
  success: z.boolean().optional(),
}).describe("Bulk invitation processed");
