/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Organization existence check completed
 */
export type CheckOrgExistsResponse = {
  success?: boolean | undefined;
  exists?: boolean | undefined;
};

export const CheckOrgExistsResponse$zodSchema: z.ZodType<
  CheckOrgExistsResponse
> = z.object({
  exists: z.boolean().optional(),
  success: z.boolean().optional(),
}).describe("Organization existence check completed");
