/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Reference to a source document cited in a response
 */
export type CitationReference = {
  citationId?: string | undefined;
  relevanceScore?: number | undefined;
  excerpt?: string | undefined;
  context?: string | undefined;
};

export const CitationReference$zodSchema: z.ZodType<CitationReference> = z
  .object({
    citationId: z.string().optional(),
    context: z.string().optional(),
    excerpt: z.string().optional(),
    relevanceScore: z.number().optional(),
  }).describe("Reference to a source document cited in a response");
