/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * JSON Schema for authentication fields
 */
export type AuthSchema = {};

export const AuthSchema$zodSchema: z.ZodType<AuthSchema> = z.object({})
  .describe("JSON Schema for authentication fields");

/**
 * JSON Schema for sync configuration
 */
export type SyncSchema = {};

export const SyncSchema$zodSchema: z.ZodType<SyncSchema> = z.object({})
  .describe("JSON Schema for sync configuration");

/**
 * JSON Schema for filter options
 */
export type FilterSchema = {};

export const FilterSchema$zodSchema: z.ZodType<FilterSchema> = z.object({})
  .describe("JSON Schema for filter options");

/**
 * Schema definition for configuring a connector type
 */
export type ConnectorSchema = {
  connectorType?: string | undefined;
  authSchema?: AuthSchema | undefined;
  syncSchema?: SyncSchema | undefined;
  filterSchema?: FilterSchema | undefined;
  requiredFields?: Array<string> | undefined;
};

export const ConnectorSchema$zodSchema: z.ZodType<ConnectorSchema> = z.object({
  authSchema: z.lazy(() => AuthSchema$zodSchema).optional(),
  connectorType: z.string().optional(),
  filterSchema: z.lazy(() => FilterSchema$zodSchema).optional(),
  requiredFields: z.array(z.string()).optional(),
  syncSchema: z.lazy(() => SyncSchema$zodSchema).optional(),
}).describe("Schema definition for configuring a connector type");
