/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Sync filter selections
 */
export type ConnectorFiltersConfigSync = {
  values?: { [k: string]: any } | undefined;
};

export const ConnectorFiltersConfigSync$zodSchema: z.ZodType<
  ConnectorFiltersConfigSync
> = z.object({
  values: z.record(z.string(), z.any()).optional(),
}).describe("Sync filter selections");

/**
 * Indexing filter selections
 */
export type Indexing = { values?: { [k: string]: any } | undefined };

export const Indexing$zodSchema: z.ZodType<Indexing> = z.object({
  values: z.record(z.string(), z.any()).optional(),
}).describe("Indexing filter selections");

/**
 * Filter configuration to control what data is synced (sync filters and indexing filters)
 */
export type ConnectorFiltersConfig = {
  sync?: ConnectorFiltersConfigSync | undefined;
  indexing?: Indexing | undefined;
};

export const ConnectorFiltersConfig$zodSchema: z.ZodType<
  ConnectorFiltersConfig
> = z.object({
  indexing: z.lazy(() => Indexing$zodSchema).optional(),
  sync: z.lazy(() => ConnectorFiltersConfigSync$zodSchema).optional(),
}).describe(
  "Filter configuration to control what data is synced (sync filters and indexing filters)",
);
