/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorAuthType,
  ConnectorAuthType$zodSchema,
} from "./connectorauthtype.js";
import { ConnectorScope, ConnectorScope$zodSchema } from "./connectorscope.js";

/**
 * A configured connector instance. Represents an active or configured
 *
 * @remarks
 * connection to an external service.
 */
export type ConnectorInstance = {
  connectorId?: string | undefined;
  connectorType?: string | undefined;
  instanceName?: string | undefined;
  scope?: ConnectorScope | undefined;
  authType?: ConnectorAuthType | undefined;
  createdBy?: string | undefined;
  orgId?: string | undefined;
  isActive?: boolean | undefined;
  isConfigured?: boolean | undefined;
  isAuthenticated?: boolean | undefined;
  syncEnabled?: boolean | undefined;
  agentEnabled?: boolean | undefined;
  lastSyncAt?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const ConnectorInstance$zodSchema: z.ZodType<ConnectorInstance> = z
  .object({
    agentEnabled: z.boolean().optional(),
    authType: ConnectorAuthType$zodSchema.optional(),
    connectorId: z.string().optional(),
    connectorType: z.string().optional(),
    createdAt: z.iso.datetime({ offset: true }).optional(),
    createdBy: z.string().optional(),
    instanceName: z.string().optional(),
    isActive: z.boolean().optional(),
    isAuthenticated: z.boolean().optional(),
    isConfigured: z.boolean().optional(),
    lastSyncAt: z.iso.datetime({ offset: true }).optional(),
    orgId: z.string().optional(),
    scope: ConnectorScope$zodSchema.optional(),
    syncEnabled: z.boolean().optional(),
    updatedAt: z.iso.datetime({ offset: true }).optional(),
  }).describe(
    "A configured connector instance. Represents an active or configured\nconnection to an external service.\n",
  );
