/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Authentication configuration for a connector instance
 */
export type ConnectorAuthConfig = {
  values?: { [k: string]: any } | undefined;
  oauthConfigId?: string | undefined;
  customValues?: { [k: string]: any } | undefined;
};

export const ConnectorAuthConfig$zodSchema: z.ZodType<ConnectorAuthConfig> = z
  .object({
    customValues: z.record(z.string(), z.any()).optional(),
    oauthConfigId: z.string().optional(),
    values: z.record(z.string(), z.any()).optional(),
  }).describe("Authentication configuration for a connector instance");
