/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Pagination information for connector lists
 */
export type ConnectorPagination = {
  page?: number | undefined;
  limit?: number | undefined;
  total?: number | undefined;
  hasMore?: boolean | undefined;
};

export const ConnectorPagination$zodSchema: z.ZodType<ConnectorPagination> = z
  .object({
    hasMore: z.boolean().optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.int().optional(),
  }).describe("Pagination information for connector lists");
