/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Toggle type: 'sync' for data synchronization, 'agent' for AI agent integration
 */
export const ConnectorToggleRequestType = {
  Sync: "sync",
  Agent: "agent",
} as const;
/**
 * Toggle type: 'sync' for data synchronization, 'agent' for AI agent integration
 */
export type ConnectorToggleRequestType = ClosedEnum<
  typeof ConnectorToggleRequestType
>;

export const ConnectorToggleRequestType$zodSchema = z.enum([
  "sync",
  "agent",
]).describe(
  "Toggle type: 'sync' for data synchronization, 'agent' for AI agent integration",
);

/**
 * Request to toggle connector active status
 */
export type ConnectorToggleRequest = { type: ConnectorToggleRequestType };

export const ConnectorToggleRequest$zodSchema: z.ZodType<
  ConnectorToggleRequest
> = z.object({
  type: ConnectorToggleRequestType$zodSchema,
}).describe("Request to toggle connector active status");
