/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorAuthType,
  ConnectorAuthType$zodSchema,
} from "./connectorauthtype.js";
import { ConnectorScope, ConnectorScope$zodSchema } from "./connectorscope.js";

/**
 * A connector type from the registry. Represents an available integration
 *
 * @remarks
 * that can be configured as a connector instance.
 */
export type ConnectorType = {
  connectorType?: string | undefined;
  displayName?: string | undefined;
  description?: string | undefined;
  appGroupId?: string | undefined;
  appGroup?: string | undefined;
  authTypes?: Array<ConnectorAuthType> | undefined;
  supportedScopes?: Array<ConnectorScope> | undefined;
  supportsSync?: boolean | undefined;
  supportsAgent?: boolean | undefined;
  supportsRealtime?: boolean | undefined;
  iconPath?: string | undefined;
  categories?: Array<string> | undefined;
  isBeta?: boolean | undefined;
};

export const ConnectorType$zodSchema: z.ZodType<ConnectorType> = z.object({
  appGroup: z.string().optional(),
  appGroupId: z.string().optional(),
  authTypes: z.array(ConnectorAuthType$zodSchema).optional(),
  categories: z.array(z.string()).optional(),
  connectorType: z.string().optional(),
  description: z.string().optional(),
  displayName: z.string().optional(),
  iconPath: z.string().optional(),
  isBeta: z.boolean().optional(),
  supportedScopes: z.array(ConnectorScope$zodSchema).optional(),
  supportsAgent: z.boolean().optional(),
  supportsRealtime: z.boolean().optional(),
  supportsSync: z.boolean().optional(),
}).describe(
  "A connector type from the registry. Represents an available integration\nthat can be configured as a connector instance.\n",
);
