/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";
import { Team, Team$zodSchema } from "./team.js";
import { UserRole, UserRole$zodSchema } from "./userrole.js";

export type CreateTeamSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const CreateTeamSecurity$zodSchema: z.ZodType<CreateTeamSecurity> = z
  .object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

/**
 * Request payload
 */
export type CreateTeamRequest = {
  name: string;
  description?: string | undefined;
  userRoles?: Array<UserRole> | undefined;
};

export const CreateTeamRequest$zodSchema: z.ZodType<CreateTeamRequest> = z
  .object({
    description: z.string().optional(),
    name: z.string(),
    userRoles: z.array(UserRole$zodSchema).optional(),
  }).describe("Request payload");

/**
 * Team created successfully
 */
export type CreateTeamResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  data?: Team | undefined;
};

export const CreateTeamResponse$zodSchema: z.ZodType<CreateTeamResponse> = z
  .object({
    data: Team$zodSchema.optional(),
    message: z.string().optional(),
    success: z.boolean().optional(),
  }).describe("Team created successfully");
