/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Filters, Filters$zodSchema } from "./filters.js";

/**
 * Request body for creating a new AI conversation.<br><br>
 *
 * @remarks
 * <b>Query Processing:</b><br>
 * The query is processed through PipesHub's AI pipeline which:
 * <ul>
 * <li>Performs semantic search across indexed knowledge bases</li>
 * <li>Retrieves relevant context from matching documents</li>
 * <li>Generates a response with citations to source materials</li>
 * <li>Suggests follow-up questions based on the conversation</li>
 * </ul>
 */
export type CreateConversationRequest = {
  query: string;
  recordIds?: Array<string> | undefined;
  departments?: Array<string> | undefined;
  filters?: Filters | undefined;
  modelKey?: string | undefined;
  modelName?: string | undefined;
  chatMode?: string | undefined;
};

export const CreateConversationRequest$zodSchema: z.ZodType<
  CreateConversationRequest
> = z.object({
  chatMode: z.string().optional(),
  departments: z.array(z.string()).optional(),
  filters: Filters$zodSchema.optional(),
  modelKey: z.string().optional(),
  modelName: z.string().optional(),
  query: z.string(),
  recordIds: z.array(z.string()).optional(),
}).describe(
  "Request body for creating a new AI conversation.<br><br>\n<b>Query Processing:</b><br>\nThe query is processed through PipesHub's AI pipeline which:\n<ul>\n<li>Performs semantic search across indexed knowledge bases</li>\n<li>Retrieves relevant context from matching documents</li>\n<li>Generates a response with citations to source materials</li>\n<li>Suggests follow-up questions based on the conversation</li>\n</ul>\n",
);
