/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorInstance,
  ConnectorInstance$zodSchema,
} from "./connectorinstance.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type CreateConnectorInstanceSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const CreateConnectorInstanceSecurity$zodSchema: z.ZodType<
  CreateConnectorInstanceSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

/**
 * Instance created
 */
export type CreateConnectorInstanceResponse = {
  success?: boolean | undefined;
  connector?: ConnectorInstance | undefined;
};

export const CreateConnectorInstanceResponse$zodSchema: z.ZodType<
  CreateConnectorInstanceResponse
> = z.object({
  connector: ConnectorInstance$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("Instance created");
