/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type CreateSubfolderSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const CreateSubfolderSecurity$zodSchema: z.ZodType<
  CreateSubfolderSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

/**
 * Request payload
 */
export type CreateSubfolderRequestBody = { folderName: string };

export const CreateSubfolderRequestBody$zodSchema: z.ZodType<
  CreateSubfolderRequestBody
> = z.object({
  folderName: z.string(),
}).describe("Request payload");

export type CreateSubfolderRequest = {
  kbId: string;
  folderId: string;
  body: CreateSubfolderRequestBody;
};

export const CreateSubfolderRequest$zodSchema: z.ZodType<
  CreateSubfolderRequest
> = z.object({
  body: z.lazy(() => CreateSubfolderRequestBody$zodSchema),
  folderId: z.string().describe("Parent folder ID"),
  kbId: z.string(),
});
