/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * JSON Schema for customization
 */
export type CreateAgentTemplateConfigSchema = {};

export const CreateAgentTemplateConfigSchema$zodSchema: z.ZodType<
  CreateAgentTemplateConfigSchema
> = z.object({}).describe("JSON Schema for customization");

/**
 * Request payload
 */
export type CreateAgentTemplateRequest = {
  name: string;
  description?: string | undefined;
  category?: string | undefined;
  defaultSystemPrompt?: string | undefined;
  recommendedTools?: Array<string> | undefined;
  configSchema?: CreateAgentTemplateConfigSchema | undefined;
  isPublic?: boolean | undefined;
};

export const CreateAgentTemplateRequest$zodSchema: z.ZodType<
  CreateAgentTemplateRequest
> = z.object({
  category: z.string().optional(),
  configSchema: z.lazy(() => CreateAgentTemplateConfigSchema$zodSchema)
    .optional(),
  defaultSystemPrompt: z.string().optional(),
  description: z.string().optional(),
  isPublic: z.boolean().default(false),
  name: z.string(),
  recommendedTools: z.array(z.string()).optional(),
}).describe("Request payload");
