/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Group type determining behavior and privileges
 */
export const CreateUserGroupType = {
  Admin: "admin",
  Standard: "standard",
  Everyone: "everyone",
  Custom: "custom",
} as const;
/**
 * Group type determining behavior and privileges
 */
export type CreateUserGroupType = ClosedEnum<typeof CreateUserGroupType>;

export const CreateUserGroupType$zodSchema = z.enum([
  "admin",
  "standard",
  "everyone",
  "custom",
]).describe("Group type determining behavior and privileges");

/**
 * Request payload
 */
export type CreateUserGroupRequest = {
  name: string;
  type: CreateUserGroupType;
  description?: string | undefined;
};

export const CreateUserGroupRequest$zodSchema: z.ZodType<
  CreateUserGroupRequest
> = z.object({
  description: z.string().optional(),
  name: z.string(),
  type: CreateUserGroupType$zodSchema,
}).describe("Request payload");
