/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Permission role to grant
 */
export const CreateKBPermissionRole = {
  Owner: "OWNER",
  Organizer: "ORGANIZER",
  Fileorganizer: "FILEORGANIZER",
  Writer: "WRITER",
  Commenter: "COMMENTER",
  Reader: "READER",
} as const;
/**
 * Permission role to grant
 */
export type CreateKBPermissionRole = ClosedEnum<typeof CreateKBPermissionRole>;

export const CreateKBPermissionRole$zodSchema = z.enum([
  "OWNER",
  "ORGANIZER",
  "FILEORGANIZER",
  "WRITER",
  "COMMENTER",
  "READER",
]).describe("Permission role to grant");

/**
 * Request payload
 */
export type CreateKBPermissionRequestBody = {
  userIds?: Array<string> | undefined;
  teamIds?: Array<string> | undefined;
  role: CreateKBPermissionRole;
};

export const CreateKBPermissionRequestBody$zodSchema: z.ZodType<
  CreateKBPermissionRequestBody
> = z.object({
  role: CreateKBPermissionRole$zodSchema,
  teamIds: z.array(z.string()).optional(),
  userIds: z.array(z.string()).optional(),
}).describe("Request payload");

export type CreateKBPermissionRequest = {
  kbId: string;
  body: CreateKBPermissionRequestBody;
};

export const CreateKBPermissionRequest$zodSchema: z.ZodType<
  CreateKBPermissionRequest
> = z.object({
  body: z.lazy(() => CreateKBPermissionRequestBody$zodSchema),
  kbId: z.string(),
});

export type PermissionResult = {
  grantedCount?: number | undefined;
  updatedCount?: number | undefined;
};

export const PermissionResult$zodSchema: z.ZodType<PermissionResult> = z.object(
  {
    grantedCount: z.int().optional(),
    updatedCount: z.int().optional(),
  },
);

/**
 * Permissions granted successfully
 */
export type CreateKBPermissionResponse = {
  kbId?: string | undefined;
  permissionResult?: PermissionResult | undefined;
};

export const CreateKBPermissionResponse$zodSchema: z.ZodType<
  CreateKBPermissionResponse
> = z.object({
  kbId: z.string().optional(),
  permissionResult: z.lazy(() => PermissionResult$zodSchema).optional(),
}).describe("Permissions granted successfully");
