/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { User, User$zodSchema } from "./user.js";

/**
 * Request payload
 */
export type CreateUserRequest = {
  fullName: string;
  email: string;
  mobile?: string | undefined;
  designation?: string | undefined;
  sendInvite?: boolean | undefined;
};

export const CreateUserRequest$zodSchema: z.ZodType<CreateUserRequest> = z
  .object({
    designation: z.string().optional(),
    email: z.string(),
    fullName: z.string(),
    mobile: z.string().optional(),
    sendInvite: z.boolean().default(true),
  }).describe("Request payload");

/**
 * User created successfully
 */
export type CreateUserResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  data?: User | undefined;
  inviteSent?: boolean | undefined;
};

export const CreateUserResponse$zodSchema: z.ZodType<CreateUserResponse> = z
  .object({
    data: User$zodSchema.optional(),
    inviteSent: z.boolean().optional(),
    message: z.string().optional(),
    success: z.boolean().optional(),
  }).describe("User created successfully");
