/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type CreateAgentSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const CreateAgentSecurity$zodSchema: z.ZodType<CreateAgentSecurity> = z
  .object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

export type CreateAgentModelConfig = {
  modelKey?: string | undefined;
  temperature?: number | undefined;
  maxTokens?: number | undefined;
};

export const CreateAgentModelConfig$zodSchema: z.ZodType<
  CreateAgentModelConfig
> = z.object({
  maxTokens: z.int().optional(),
  modelKey: z.string().optional(),
  temperature: z.number().optional(),
});

/**
 * Request payload
 */
export type CreateAgentRequest = {
  name: string;
  description?: string | undefined;
  systemPrompt?: string | undefined;
  tools?: Array<string> | undefined;
  knowledgeBases?: Array<string> | undefined;
  modelConfig?: CreateAgentModelConfig | undefined;
  isPublic?: boolean | undefined;
};

export const CreateAgentRequest$zodSchema: z.ZodType<CreateAgentRequest> = z
  .object({
    description: z.string().optional(),
    isPublic: z.boolean().default(false),
    knowledgeBases: z.array(z.string()).optional(),
    modelConfig: z.lazy(() => CreateAgentModelConfig$zodSchema).optional(),
    name: z.string(),
    systemPrompt: z.string().optional(),
    tools: z.array(z.string()).optional(),
  }).describe("Request payload");
