/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type DeleteUserSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const DeleteUserSecurity$zodSchema: z.ZodType<DeleteUserSecurity> = z
  .object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

export type DeleteUserRequest = { id: string };

export const DeleteUserRequest$zodSchema: z.ZodType<DeleteUserRequest> = z
  .object({
    id: z.string().describe("User ID (24-character MongoDB ObjectId)"),
  });

export type DeletedUser = {
  _id?: string | undefined;
  fullName?: string | undefined;
  email?: string | undefined;
};

export const DeletedUser$zodSchema: z.ZodType<DeletedUser> = z.object({
  _id: z.string().optional(),
  email: z.string().optional(),
  fullName: z.string().optional(),
});

/**
 * User deleted successfully
 */
export type DeleteUserResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  deletedUser?: DeletedUser | undefined;
};

export const DeleteUserResponse$zodSchema: z.ZodType<DeleteUserResponse> = z
  .object({
    deletedUser: z.lazy(() => DeletedUser$zodSchema).optional(),
    message: z.string().optional(),
    success: z.boolean().optional(),
  }).describe("User deleted successfully");
