/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type DeleteAgentSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const DeleteAgentSecurity$zodSchema: z.ZodType<DeleteAgentSecurity> = z
  .object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

export type DeleteAgentRequest = { agentKey: string };

export const DeleteAgentRequest$zodSchema: z.ZodType<DeleteAgentRequest> = z
  .object({
    agentKey: z.string(),
  });
