/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type DeleteConnectorInstanceSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const DeleteConnectorInstanceSecurity$zodSchema: z.ZodType<
  DeleteConnectorInstanceSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type DeleteConnectorInstanceRequest = { connectorId: string };

export const DeleteConnectorInstanceRequest$zodSchema: z.ZodType<
  DeleteConnectorInstanceRequest
> = z.object({
  connectorId: z.string(),
});

/**
 * Connector deleted
 */
export type DeleteConnectorInstanceResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

export const DeleteConnectorInstanceResponse$zodSchema: z.ZodType<
  DeleteConnectorInstanceResponse
> = z.object({
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Connector deleted");
