/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteOAuthAppRequest = { appId: string };

export const DeleteOAuthAppRequest$zodSchema: z.ZodType<DeleteOAuthAppRequest> =
  z.object({
    appId: z.string().describe("OAuth app ID"),
  });

/**
 * OAuth app deleted
 */
export type DeleteOAuthAppResponse = { message?: string | undefined };

export const DeleteOAuthAppResponse$zodSchema: z.ZodType<
  DeleteOAuthAppResponse
> = z.object({
  message: z.string().optional(),
}).describe("OAuth app deleted");
