/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteUserGroupRequest = { groupId: string };

export const DeleteUserGroupRequest$zodSchema: z.ZodType<
  DeleteUserGroupRequest
> = z.object({
  groupId: z.string().describe("Unique identifier of the user group to delete"),
});

/**
 * User group deleted successfully
 */
export type DeleteUserGroupResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

export const DeleteUserGroupResponse$zodSchema: z.ZodType<
  DeleteUserGroupResponse
> = z.object({
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("User group deleted successfully");
