/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type DeleteAllSearchHistorySecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const DeleteAllSearchHistorySecurity$zodSchema: z.ZodType<
  DeleteAllSearchHistorySecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

/**
 * Search history cleared
 */
export type DeleteAllSearchHistoryResponse = { message?: string | undefined };

export const DeleteAllSearchHistoryResponse$zodSchema: z.ZodType<
  DeleteAllSearchHistoryResponse
> = z.object({
  message: z.string().optional(),
}).describe("Search history cleared");
