/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type DeleteKnowledgeBaseSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const DeleteKnowledgeBaseSecurity$zodSchema: z.ZodType<
  DeleteKnowledgeBaseSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type DeleteKnowledgeBaseRequest = { kbId: string };

export const DeleteKnowledgeBaseRequest$zodSchema: z.ZodType<
  DeleteKnowledgeBaseRequest
> = z.object({
  kbId: z.string().describe("Knowledge base ID"),
});

/**
 * Knowledge base deleted successfully
 */
export type DeleteKnowledgeBaseResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

export const DeleteKnowledgeBaseResponse$zodSchema: z.ZodType<
  DeleteKnowledgeBaseResponse
> = z.object({
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Knowledge base deleted successfully");
