/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteOAuthConfigRequest = {
  connectorType: string;
  configId: string;
};

export const DeleteOAuthConfigRequest$zodSchema: z.ZodType<
  DeleteOAuthConfigRequest
> = z.object({
  configId: z.string(),
  connectorType: z.string(),
});

/**
 * OAuth configuration deleted
 */
export type DeleteOAuthConfigResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

export const DeleteOAuthConfigResponse$zodSchema: z.ZodType<
  DeleteOAuthConfigResponse
> = z.object({
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("OAuth configuration deleted");
