/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type DeleteConversationByIdSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const DeleteConversationByIdSecurity$zodSchema: z.ZodType<
  DeleteConversationByIdSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type DeleteConversationByIdRequest = { conversationId: string };

export const DeleteConversationByIdRequest$zodSchema: z.ZodType<
  DeleteConversationByIdRequest
> = z.object({
  conversationId: z.string().describe("Unique conversation identifier"),
});

/**
 * Conversation deleted successfully
 */
export type DeleteConversationByIdResponse = { message?: string | undefined };

export const DeleteConversationByIdResponse$zodSchema: z.ZodType<
  DeleteConversationByIdResponse
> = z.object({
  message: z.string().optional(),
}).describe("Conversation deleted successfully");
