/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Platform feature flag definition
 */
export type FeatureFlag = {
  key?: string | undefined;
  label?: string | undefined;
  description?: string | undefined;
  defaultEnabled?: boolean | undefined;
};

export const FeatureFlag$zodSchema: z.ZodType<FeatureFlag> = z.object({
  defaultEnabled: z.boolean().optional(),
  description: z.string().optional(),
  key: z.string().optional(),
  label: z.string().optional(),
}).describe("Platform feature flag definition");
