/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AppType, AppType$zodSchema } from "./apptype.js";

export type Filters = {
  apps?: Array<AppType> | undefined;
  kb?: Array<string> | undefined;
};

export const Filters$zodSchema: z.ZodType<Filters> = z.object({
  apps: z.array(AppType$zodSchema).optional(),
  kb: z.array(z.string()).optional(),
});
