/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Folder = {
  _key?: string | undefined;
  name: string;
  parentId?: string | undefined;
  kbId: string;
  orgId: string;
  createdAtTimestamp?: number | undefined;
  updatedAtTimestamp?: number | undefined;
  isDeleted?: boolean | undefined;
};

export const Folder$zodSchema: z.ZodType<Folder> = z.object({
  _key: z.string().optional(),
  createdAtTimestamp: z.int().optional(),
  isDeleted: z.boolean().default(false),
  kbId: z.string(),
  name: z.string(),
  orgId: z.string(),
  parentId: z.string().optional(),
  updatedAtTimestamp: z.int().optional(),
});
