/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request to send password reset email
 */
export type ForgotPasswordRequest = {
  email: string;
  cfTurnstileResponse?: string | undefined;
};

export const ForgotPasswordRequest$zodSchema: z.ZodType<ForgotPasswordRequest> =
  z.object({
    cfTurnstileResponse: z.string().optional(),
    email: z.string(),
  }).describe("Request to send password reset email");
