/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Generic OAuth 2.0 provider configuration
 */
export type GenericOAuthConfig = {
  providerName: string;
  clientId: string;
  clientSecret?: string | undefined;
  authorizationUrl?: string | undefined;
  tokenEndpoint?: string | undefined;
  userInfoEndpoint?: string | undefined;
  scope?: string | undefined;
  redirectUri?: string | undefined;
};

export const GenericOAuthConfig$zodSchema: z.ZodType<GenericOAuthConfig> = z
  .object({
    authorizationUrl: z.string().optional(),
    clientId: z.string(),
    clientSecret: z.string().optional(),
    providerName: z.string(),
    redirectUri: z.string().optional(),
    scope: z.string().optional(),
    tokenEndpoint: z.string().optional(),
    userInfoEndpoint: z.string().optional(),
  }).describe("Generic OAuth 2.0 provider configuration");
