/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";
import { User, User$zodSchema } from "./user.js";

export type GetAllUsersSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetAllUsersSecurity$zodSchema: z.ZodType<GetAllUsersSecurity> = z
  .object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

export type GetAllUsersRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
};

export const GetAllUsersRequest$zodSchema: z.ZodType<GetAllUsersRequest> = z
  .object({
    limit: z.int().default(50).describe("Number of users per page"),
    page: z.int().default(1).describe("Page number for pagination (1-based)"),
    search: z.string().describe("Search users by name or email").optional(),
  });

export type GetAllUsersPagination = {
  page?: number | undefined;
  limit?: number | undefined;
  total?: number | undefined;
  totalPages?: number | undefined;
};

export const GetAllUsersPagination$zodSchema: z.ZodType<GetAllUsersPagination> =
  z.object({
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.int().optional(),
    totalPages: z.int().optional(),
  });

/**
 * List of users retrieved successfully
 */
export type GetAllUsersResponse = {
  success?: boolean | undefined;
  data?: Array<User> | undefined;
  pagination?: GetAllUsersPagination | undefined;
};

export const GetAllUsersResponse$zodSchema: z.ZodType<GetAllUsersResponse> = z
  .object({
    data: z.array(User$zodSchema).optional(),
    pagination: z.lazy(() => GetAllUsersPagination$zodSchema).optional(),
    success: z.boolean().optional(),
  }).describe("List of users retrieved successfully");
