/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FilterOptions, FilterOptions$zodSchema } from "./filteroptions.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type GetConnectorFiltersSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetConnectorFiltersSecurity$zodSchema: z.ZodType<
  GetConnectorFiltersSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type GetConnectorFiltersRequest = { connectorId: string };

export const GetConnectorFiltersRequest$zodSchema: z.ZodType<
  GetConnectorFiltersRequest
> = z.object({
  connectorId: z.string(),
});

/**
 * Filter options retrieved
 */
export type GetConnectorFiltersResponse = {
  success?: boolean | undefined;
  filterOptions?: FilterOptions | undefined;
};

export const GetConnectorFiltersResponse$zodSchema: z.ZodType<
  GetConnectorFiltersResponse
> = z.object({
  filterOptions: FilterOptions$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("Filter options retrieved");
