/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type GetConnectorStatsSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetConnectorStatsSecurity$zodSchema: z.ZodType<
  GetConnectorStatsSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type GetConnectorStatsRequest = { connectorId: string };

export const GetConnectorStatsRequest$zodSchema: z.ZodType<
  GetConnectorStatsRequest
> = z.object({
  connectorId: z.string().describe("Connector ID"),
});
