/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorConfig,
  ConnectorConfig$zodSchema,
} from "./connectorconfig.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type GetConnectorConfigSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetConnectorConfigSecurity$zodSchema: z.ZodType<
  GetConnectorConfigSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type GetConnectorConfigRequest = { connectorId: string };

export const GetConnectorConfigRequest$zodSchema: z.ZodType<
  GetConnectorConfigRequest
> = z.object({
  connectorId: z.string(),
});

/**
 * Configuration retrieved
 */
export type GetConnectorConfigResponse = {
  success?: boolean | undefined;
  config?: ConnectorConfig | undefined;
};

export const GetConnectorConfigResponse$zodSchema: z.ZodType<
  GetConnectorConfigResponse
> = z.object({
  config: ConnectorConfig$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("Configuration retrieved");
