/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { JobStatus, JobStatus$zodSchema } from "./jobstatus.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type GetCrawlingJobStatusSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetCrawlingJobStatusSecurity$zodSchema: z.ZodType<
  GetCrawlingJobStatusSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type GetCrawlingJobStatusRequest = {
  connector: string;
  connectorId: string;
};

export const GetCrawlingJobStatusRequest$zodSchema: z.ZodType<
  GetCrawlingJobStatusRequest
> = z.object({
  connector: z.string().describe("Connector type identifier"),
  connectorId: z.string().describe(
    "Unique identifier of the connector instance",
  ),
});

/**
 * Job status retrieved successfully
 */
export type GetCrawlingJobStatusResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  data?: JobStatus | undefined;
};

export const GetCrawlingJobStatusResponse$zodSchema: z.ZodType<
  GetCrawlingJobStatusResponse
> = z.object({
  data: JobStatus$zodSchema.optional(),
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Job status retrieved successfully");
