/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type GetFolderContentsSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetFolderContentsSecurity$zodSchema: z.ZodType<
  GetFolderContentsSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export const GetFolderContentsSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetFolderContentsSortOrder = ClosedEnum<
  typeof GetFolderContentsSortOrder
>;

export const GetFolderContentsSortOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type GetFolderContentsRequest = {
  kbId: string;
  folderId: string;
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
  sortBy?: string | undefined;
  sortOrder?: GetFolderContentsSortOrder | undefined;
};

export const GetFolderContentsRequest$zodSchema: z.ZodType<
  GetFolderContentsRequest
> = z.object({
  folderId: z.string().describe("Folder ID"),
  kbId: z.string().describe("Knowledge base ID"),
  limit: z.int().default(20),
  page: z.int().default(1),
  search: z.string().optional(),
  sortBy: z.string().default("createdAtTimestamp"),
  sortOrder: GetFolderContentsSortOrder$zodSchema.default("desc"),
});
