/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { UserGroup, UserGroup$zodSchema } from "./usergroup.js";

export type GetGroupsForUserRequest = { userId: string };

export const GetGroupsForUserRequest$zodSchema: z.ZodType<
  GetGroupsForUserRequest
> = z.object({
  userId: z.string().describe("Unique identifier of the user"),
});

/**
 * User's groups retrieved successfully
 */
export type GetGroupsForUserResponse = {
  success?: boolean | undefined;
  data?: Array<UserGroup> | undefined;
};

export const GetGroupsForUserResponse$zodSchema: z.ZodType<
  GetGroupsForUserResponse
> = z.object({
  data: z.array(UserGroup$zodSchema).optional(),
  success: z.boolean().optional(),
}).describe("User's groups retrieved successfully");
