/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type GetOAuthAuthorizationUrlSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetOAuthAuthorizationUrlSecurity$zodSchema: z.ZodType<
  GetOAuthAuthorizationUrlSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type GetOAuthAuthorizationUrlRequest = {
  connectorId: string;
  baseUrl?: string | undefined;
};

export const GetOAuthAuthorizationUrlRequest$zodSchema: z.ZodType<
  GetOAuthAuthorizationUrlRequest
> = z.object({
  baseUrl: z.string().describe("Base URL for self-hosted instances").optional(),
  connectorId: z.string(),
});

/**
 * Authorization URL generated
 */
export type GetOAuthAuthorizationUrlResponse = {
  success?: boolean | undefined;
  authorizationUrl?: string | undefined;
  state?: string | undefined;
};

export const GetOAuthAuthorizationUrlResponse$zodSchema: z.ZodType<
  GetOAuthAuthorizationUrlResponse
> = z.object({
  authorizationUrl: z.string().optional(),
  state: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Authorization URL generated");
