/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorPagination,
  ConnectorPagination$zodSchema,
} from "./connectorpagination.js";
import { ConnectorType, ConnectorType$zodSchema } from "./connectortype.js";

export type GetOAuthRegistryRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
};

export const GetOAuthRegistryRequest$zodSchema: z.ZodType<
  GetOAuthRegistryRequest
> = z.object({
  limit: z.int().default(20),
  page: z.int().default(1),
  search: z.string().optional(),
});

/**
 * OAuth connector types retrieved
 */
export type GetOAuthRegistryResponse = {
  success?: boolean | undefined;
  connectors?: Array<ConnectorType> | undefined;
  pagination?: ConnectorPagination | undefined;
};

export const GetOAuthRegistryResponse$zodSchema: z.ZodType<
  GetOAuthRegistryResponse
> = z.object({
  connectors: z.array(ConnectorType$zodSchema).optional(),
  pagination: ConnectorPagination$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("OAuth connector types retrieved");
