/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type GetOrganizationLogoSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetOrganizationLogoSecurity$zodSchema: z.ZodType<
  GetOrganizationLogoSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

/**
 * Logo URL retrieved successfully
 */
export type GetOrganizationLogoResponse = {
  success?: boolean | undefined;
  hasLogo?: boolean | undefined;
  logoUrl?: string | undefined;
};

export const GetOrganizationLogoResponse$zodSchema: z.ZodType<
  GetOrganizationLogoResponse
> = z.object({
  hasLogo: z.boolean().optional(),
  logoUrl: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Logo URL retrieved successfully");
