/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ConnectorType, ConnectorType$zodSchema } from "./connectortype.js";

export type GetOAuthConnectorTypeRequest = { connectorType: string };

export const GetOAuthConnectorTypeRequest$zodSchema: z.ZodType<
  GetOAuthConnectorTypeRequest
> = z.object({
  connectorType: z.string(),
});

/**
 * Connector type retrieved
 */
export type GetOAuthConnectorTypeResponse = {
  success?: boolean | undefined;
  connector?: ConnectorType | undefined;
};

export const GetOAuthConnectorTypeResponse$zodSchema: z.ZodType<
  GetOAuthConnectorTypeResponse
> = z.object({
  connector: ConnectorType$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("Connector type retrieved");
