/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type GetRecordByIdSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetRecordByIdSecurity$zodSchema: z.ZodType<GetRecordByIdSecurity> =
  z.object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

export type GetRecordByIdRequest = {
  recordId: string;
  convertTo?: string | undefined;
};

export const GetRecordByIdRequest$zodSchema: z.ZodType<GetRecordByIdRequest> = z
  .object({
    convertTo: z.string().describe("Optional format to convert the file to")
      .optional(),
    recordId: z.string().describe("Record ID"),
  });
