/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";
import { Team, Team$zodSchema } from "./team.js";

export type GetTeamByIdSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetTeamByIdSecurity$zodSchema: z.ZodType<GetTeamByIdSecurity> = z
  .object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

export type GetTeamByIdRequest = { teamId: string };

export const GetTeamByIdRequest$zodSchema: z.ZodType<GetTeamByIdRequest> = z
  .object({
    teamId: z.string().describe("Team ID (24-character MongoDB ObjectId)"),
  });

/**
 * Team details retrieved successfully
 */
export type GetTeamByIdResponse = {
  success?: boolean | undefined;
  data?: Team | undefined;
};

export const GetTeamByIdResponse$zodSchema: z.ZodType<GetTeamByIdResponse> = z
  .object({
    data: Team$zodSchema.optional(),
    success: z.boolean().optional(),
  }).describe("Team details retrieved successfully");
