/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";

export type GetUserDisplayPictureResponse =
  | Uint8Array
  | string
  | Uint8Array
  | string;

export const GetUserDisplayPictureResponse$zodSchema: z.ZodType<
  GetUserDisplayPictureResponse
> = z.union([
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
]);
