/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";
import { User, User$zodSchema } from "./user.js";

export type GetUserByIdSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const GetUserByIdSecurity$zodSchema: z.ZodType<GetUserByIdSecurity> = z
  .object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

export type GetUserByIdRequest = { id: string };

export const GetUserByIdRequest$zodSchema: z.ZodType<GetUserByIdRequest> = z
  .object({
    id: z.string().describe("User ID (24-character MongoDB ObjectId)"),
  });

/**
 * User details retrieved successfully
 */
export type GetUserByIdResponse = {
  success?: boolean | undefined;
  data?: User | undefined;
};

export const GetUserByIdResponse$zodSchema: z.ZodType<GetUserByIdResponse> = z
  .object({
    data: User$zodSchema.optional(),
    success: z.boolean().optional(),
  }).describe("User details retrieved successfully");
