/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type HandleToolsetOAuthCallbackRequest = {
  code?: string | undefined;
  state?: string | undefined;
  error?: string | undefined;
  base_url?: string | undefined;
};

export const HandleToolsetOAuthCallbackRequest$zodSchema: z.ZodType<
  HandleToolsetOAuthCallbackRequest
> = z.object({
  base_url: z.string().optional(),
  code: z.string().optional(),
  error: z.string().optional(),
  state: z.string().optional(),
});

/**
 * OAuth callback handled successfully
 */
export type HandleToolsetOAuthCallbackResponse = {
  redirectUrl?: string | undefined;
};

export const HandleToolsetOAuthCallbackResponse$zodSchema: z.ZodType<
  HandleToolsetOAuthCallbackResponse
> = z.object({
  redirectUrl: z.string().optional(),
}).describe("OAuth callback handled successfully");
