/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type HandleOAuthCallbackRequest = {
  code?: string | undefined;
  state?: string | undefined;
  error?: string | undefined;
  baseUrl?: string | undefined;
};

export const HandleOAuthCallbackRequest$zodSchema: z.ZodType<
  HandleOAuthCallbackRequest
> = z.object({
  baseUrl: z.string().describe("Base URL for redirect").optional(),
  code: z.string().describe("Authorization code from provider").optional(),
  error: z.string().describe("Error code if authorization failed").optional(),
  state: z.string().describe("State parameter (contains connector ID)")
    .optional(),
});

export type HandleOAuthCallbackResponse = {
  Headers: { [k: string]: Array<string> };
};

export const HandleOAuthCallbackResponse$zodSchema: z.ZodType<
  HandleOAuthCallbackResponse
> = z.object({
  Headers: z.record(z.string(), z.array(z.string())).default({}),
});
