/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthProviders, AuthProviders$zodSchema } from "./authproviders.js";

export const InitAuthResponseAllowedMethod = {
  SamlSso: "samlSso",
  Otp: "otp",
  Password: "password",
  Google: "google",
  Microsoft: "microsoft",
  AzureAd: "azureAd",
  Oauth: "oauth",
} as const;
export type InitAuthResponseAllowedMethod = ClosedEnum<
  typeof InitAuthResponseAllowedMethod
>;

export const InitAuthResponseAllowedMethod$zodSchema = z.enum([
  "samlSso",
  "otp",
  "password",
  "google",
  "microsoft",
  "azureAd",
  "oauth",
]);

/**
 * Response containing available authentication methods and session info
 */
export type InitAuthResponse = {
  currentStep?: number | undefined;
  allowedMethods?: Array<InitAuthResponseAllowedMethod> | undefined;
  message?: string | undefined;
  authProviders?: AuthProviders | undefined;
};

export const InitAuthResponse$zodSchema: z.ZodType<InitAuthResponse> = z.object(
  {
    allowedMethods: z.array(InitAuthResponseAllowedMethod$zodSchema).optional(),
    authProviders: AuthProviders$zodSchema.optional(),
    currentStep: z.int().optional(),
    message: z.string().optional(),
  },
).describe(
  "Response containing available authentication methods and session info",
);
