/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import {
  InitAuthResponse,
  InitAuthResponse$zodSchema,
} from "./initauthresponse.js";

export type InitAuthResponseResult = InitAuthResponse | AuthError;

export const InitAuthResponseResult$zodSchema: z.ZodType<
  InitAuthResponseResult
> = z.union([
  InitAuthResponse$zodSchema,
  AuthError$zodSchema,
]);

export type InitAuthResponseResponse = {
  Headers: { [k: string]: Array<string> };
  Result: InitAuthResponse | AuthError;
};

export const InitAuthResponseResponse$zodSchema: z.ZodType<
  InitAuthResponseResponse
> = z.object({
  Headers: z.record(z.string(), z.array(z.string())).default({}),
  Result: z.union([
    InitAuthResponse$zodSchema,
    AuthError$zodSchema,
  ]),
});
