/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorInstance,
  ConnectorInstance$zodSchema,
} from "./connectorinstance.js";
import {
  ConnectorPagination,
  ConnectorPagination$zodSchema,
} from "./connectorpagination.js";
import { ConnectorScope, ConnectorScope$zodSchema } from "./connectorscope.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type ListActiveAgentConnectorsSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const ListActiveAgentConnectorsSecurity$zodSchema: z.ZodType<
  ListActiveAgentConnectorsSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type ListActiveAgentConnectorsRequest = {
  scope?: ConnectorScope | undefined;
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
};

export const ListActiveAgentConnectorsRequest$zodSchema: z.ZodType<
  ListActiveAgentConnectorsRequest
> = z.object({
  limit: z.int().default(20),
  page: z.int().default(1),
  scope: ConnectorScope$zodSchema.optional(),
  search: z.string().optional(),
});

/**
 * Active agent connectors retrieved
 */
export type ListActiveAgentConnectorsResponse = {
  success?: boolean | undefined;
  connectors?: Array<ConnectorInstance> | undefined;
  pagination?: ConnectorPagination | undefined;
};

export const ListActiveAgentConnectorsResponse$zodSchema: z.ZodType<
  ListActiveAgentConnectorsResponse
> = z.object({
  connectors: z.array(ConnectorInstance$zodSchema).optional(),
  pagination: ConnectorPagination$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("Active agent connectors retrieved");
