/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";
import { User, User$zodSchema } from "./user.js";

export type ListUsersGraphSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const ListUsersGraphSecurity$zodSchema: z.ZodType<
  ListUsersGraphSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

/**
 * Field to sort by
 */
export const ListUsersGraphSortBy = {
  FullName: "fullName",
  Email: "email",
  CreatedAt: "createdAt",
} as const;
/**
 * Field to sort by
 */
export type ListUsersGraphSortBy = ClosedEnum<typeof ListUsersGraphSortBy>;

export const ListUsersGraphSortBy$zodSchema = z.enum([
  "fullName",
  "email",
  "createdAt",
]).describe("Field to sort by");

/**
 * Sort direction
 */
export const ListUsersGraphSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort direction
 */
export type ListUsersGraphSortOrder = ClosedEnum<
  typeof ListUsersGraphSortOrder
>;

export const ListUsersGraphSortOrder$zodSchema = z.enum([
  "asc",
  "desc",
]).describe("Sort direction");

export type ListUsersGraphRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
  sortBy?: ListUsersGraphSortBy | undefined;
  sortOrder?: ListUsersGraphSortOrder | undefined;
};

export const ListUsersGraphRequest$zodSchema: z.ZodType<ListUsersGraphRequest> =
  z.object({
    limit: z.int().default(10).describe("Number of results per page"),
    page: z.int().default(1).describe("Page number (1-based)"),
    search: z.string().describe("Search query (searches name and email)")
      .optional(),
    sortBy: ListUsersGraphSortBy$zodSchema.default("fullName"),
    sortOrder: ListUsersGraphSortOrder$zodSchema.default("asc"),
  });

export type ListUsersGraphPagination = {
  page?: number | undefined;
  limit?: number | undefined;
  total?: number | undefined;
  totalPages?: number | undefined;
};

export const ListUsersGraphPagination$zodSchema: z.ZodType<
  ListUsersGraphPagination
> = z.object({
  limit: z.int().optional(),
  page: z.int().optional(),
  total: z.int().optional(),
  totalPages: z.int().optional(),
});

/**
 * Paginated list of users
 */
export type ListUsersGraphResponse = {
  success?: boolean | undefined;
  data?: Array<User> | undefined;
  pagination?: ListUsersGraphPagination | undefined;
  total?: number | undefined;
  page?: number | undefined;
  limit?: number | undefined;
};

export const ListUsersGraphResponse$zodSchema: z.ZodType<
  ListUsersGraphResponse
> = z.object({
  data: z.array(User$zodSchema).optional(),
  limit: z.int().optional(),
  page: z.int().optional(),
  pagination: z.lazy(() => ListUsersGraphPagination$zodSchema).optional(),
  success: z.boolean().optional(),
  total: z.int().optional(),
}).describe("Paginated list of users");
