/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Filter by status
 */
export const ListOAuthAppsStatus = {
  Active: "active",
  Suspended: "suspended",
  Revoked: "revoked",
} as const;
/**
 * Filter by status
 */
export type ListOAuthAppsStatus = ClosedEnum<typeof ListOAuthAppsStatus>;

export const ListOAuthAppsStatus$zodSchema = z.enum([
  "active",
  "suspended",
  "revoked",
]).describe("Filter by status");

export type ListOAuthAppsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  status?: ListOAuthAppsStatus | undefined;
  search?: string | undefined;
};

export const ListOAuthAppsRequest$zodSchema: z.ZodType<ListOAuthAppsRequest> = z
  .object({
    limit: z.int().default(20).describe("Items per page"),
    page: z.int().default(1).describe("Page number"),
    search: z.string().describe("Search by app name").optional(),
    status: ListOAuthAppsStatus$zodSchema.optional(),
  });
