/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorInstance,
  ConnectorInstance$zodSchema,
} from "./connectorinstance.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type ListActiveConnectorsSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const ListActiveConnectorsSecurity$zodSchema: z.ZodType<
  ListActiveConnectorsSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

/**
 * Active connectors retrieved
 */
export type ListActiveConnectorsResponse = {
  success?: boolean | undefined;
  connectors?: Array<ConnectorInstance> | undefined;
};

export const ListActiveConnectorsResponse$zodSchema: z.ZodType<
  ListActiveConnectorsResponse
> = z.object({
  connectors: z.array(ConnectorInstance$zodSchema).optional(),
  success: z.boolean().optional(),
}).describe("Active connectors retrieved");
