/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorPagination,
  ConnectorPagination$zodSchema,
} from "./connectorpagination.js";
import { OAuthConfig, OAuthConfig$zodSchema } from "./oauthconfig.js";

export type ListOAuthConfigsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
};

export const ListOAuthConfigsRequest$zodSchema: z.ZodType<
  ListOAuthConfigsRequest
> = z.object({
  limit: z.int().default(20),
  page: z.int().default(1),
  search: z.string().optional(),
});

/**
 * OAuth configurations retrieved
 */
export type ListOAuthConfigsResponse = {
  success?: boolean | undefined;
  oauthConfigs?: Array<OAuthConfig> | undefined;
  pagination?: ConnectorPagination | undefined;
};

export const ListOAuthConfigsResponse$zodSchema: z.ZodType<
  ListOAuthConfigsResponse
> = z.object({
  oauthConfigs: z.array(OAuthConfig$zodSchema).optional(),
  pagination: ConnectorPagination$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("OAuth configurations retrieved");
