/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Logged out successfully
 */
export type LogoutResponse = { message?: string | undefined };

export const LogoutResponse$zodSchema: z.ZodType<LogoutResponse> = z.object({
  message: z.string().optional(),
}).describe("Logged out successfully");
