/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type Ratings = {
  accuracy?: number | undefined;
  relevance?: number | undefined;
  completeness?: number | undefined;
  clarity?: number | undefined;
};

export const Ratings$zodSchema: z.ZodType<Ratings> = z.object({
  accuracy: z.int().optional(),
  clarity: z.int().optional(),
  completeness: z.int().optional(),
  relevance: z.int().optional(),
});

export const Category = {
  IncorrectInformation: "incorrect_information",
  MissingInformation: "missing_information",
  OutdatedInformation: "outdated_information",
  IrrelevantResponse: "irrelevant_response",
  TooVerbose: "too_verbose",
  TooBrief: "too_brief",
  FormattingIssues: "formatting_issues",
  CitationIssues: "citation_issues",
} as const;
export type Category = ClosedEnum<typeof Category>;

export const Category$zodSchema = z.enum([
  "incorrect_information",
  "missing_information",
  "outdated_information",
  "irrelevant_response",
  "too_verbose",
  "too_brief",
  "formatting_issues",
  "citation_issues",
]);

export type Comments = {
  positive?: string | undefined;
  negative?: string | undefined;
  suggestions?: string | undefined;
};

export const Comments$zodSchema: z.ZodType<Comments> = z.object({
  negative: z.string().optional(),
  positive: z.string().optional(),
  suggestions: z.string().optional(),
});

export type CitationFeedback = {
  citationId?: string | undefined;
  isRelevant?: boolean | undefined;
  relevanceScore?: number | undefined;
  comment?: string | undefined;
};

export const CitationFeedback$zodSchema: z.ZodType<CitationFeedback> = z.object(
  {
    citationId: z.string().optional(),
    comment: z.string().optional(),
    isRelevant: z.boolean().optional(),
    relevanceScore: z.int().optional(),
  },
);

/**
 * Comprehensive feedback on an AI response. Feedback helps improve
 *
 * @remarks
 * the AI's performance and response quality over time.
 */
export type MessageFeedback = {
  isHelpful?: boolean | undefined;
  ratings?: Ratings | undefined;
  categories?: Array<Category> | undefined;
  comments?: Comments | undefined;
  citationFeedback?: Array<CitationFeedback> | undefined;
  followUpQuestionsHelpful?: boolean | undefined;
};

export const MessageFeedback$zodSchema: z.ZodType<MessageFeedback> = z.object({
  categories: z.array(Category$zodSchema).optional(),
  citationFeedback: z.array(z.lazy(() => CitationFeedback$zodSchema))
    .optional(),
  comments: z.lazy(() => Comments$zodSchema).optional(),
  followUpQuestionsHelpful: z.boolean().optional(),
  isHelpful: z.boolean().optional(),
  ratings: z.lazy(() => Ratings$zodSchema).optional(),
}).describe(
  "Comprehensive feedback on an AI response. Feedback helps improve\nthe AI's performance and response quality over time.\n",
);
