/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Configuration for application telemetry and metrics collection.
 *
 * @remarks
 * Metrics are collected anonymously and pushed to a remote server for analytics.
 */
export type MetricsCollectionConfig = {
  enableMetricCollection?: boolean | undefined;
  pushIntervalMs?: number | undefined;
  serverUrl?: string | undefined;
  apiKey?: string | undefined;
  instanceId?: string | undefined;
  appVersion?: string | undefined;
};

export const MetricsCollectionConfig$zodSchema: z.ZodType<
  MetricsCollectionConfig
> = z.object({
  apiKey: z.string().optional(),
  appVersion: z.string().optional(),
  enableMetricCollection: z.boolean().optional(),
  instanceId: z.string().optional(),
  pushIntervalMs: z.int().default(60000),
  serverUrl: z.string().optional(),
}).describe(
  "Configuration for application telemetry and metrics collection.\nMetrics are collected anonymously and pushed to a remote server for analytics.\n",
);
