/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Microsoft authentication configuration
 */
export type MicrosoftAuthConfig = {
  clientId: string;
  tenantId?: string | undefined;
};

export const MicrosoftAuthConfig$zodSchema: z.ZodType<MicrosoftAuthConfig> = z
  .object({
    clientId: z.string(),
    tenantId: z.string().default("common"),
  }).describe("Microsoft authentication configuration");
