/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * App status
 */
export const OAuthAppWithSecretStatus = {
  Active: "active",
  Suspended: "suspended",
  Revoked: "revoked",
} as const;
/**
 * App status
 */
export type OAuthAppWithSecretStatus = ClosedEnum<
  typeof OAuthAppWithSecretStatus
>;

export const OAuthAppWithSecretStatus$zodSchema = z.enum([
  "active",
  "suspended",
  "revoked",
]).describe("App status");

/**
 * OAuth app details (without secret)
 */
export type OAuthAppWithSecret = {
  id?: string | undefined;
  slug?: string | undefined;
  clientId?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  redirectUris?: Array<string> | undefined;
  allowedGrantTypes?: Array<string> | undefined;
  allowedScopes?: Array<string> | undefined;
  status?: OAuthAppWithSecretStatus | undefined;
  logoUrl?: string | undefined;
  homepageUrl?: string | undefined;
  privacyPolicyUrl?: string | undefined;
  termsOfServiceUrl?: string | undefined;
  isConfidential?: boolean | undefined;
  accessTokenLifetime?: number | undefined;
  refreshTokenLifetime?: number | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  clientSecret: string;
};

export const OAuthAppWithSecret$zodSchema: z.ZodType<OAuthAppWithSecret> = z
  .object({
    accessTokenLifetime: z.int().optional(),
    allowedGrantTypes: z.array(z.string()).optional(),
    allowedScopes: z.array(z.string()).optional(),
    clientId: z.string().optional(),
    clientSecret: z.string(),
    createdAt: z.iso.datetime({ offset: true }).optional(),
    description: z.string().optional(),
    homepageUrl: z.string().optional(),
    id: z.string().optional(),
    isConfidential: z.boolean().optional(),
    logoUrl: z.string().optional(),
    name: z.string().optional(),
    privacyPolicyUrl: z.string().optional(),
    redirectUris: z.array(z.string()).optional(),
    refreshTokenLifetime: z.int().optional(),
    slug: z.string().optional(),
    status: OAuthAppWithSecretStatus$zodSchema.optional(),
    termsOfServiceUrl: z.string().optional(),
    updatedAt: z.iso.datetime({ offset: true }).optional(),
  }).describe("OAuth app details (without secret)");
