/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * OAuth credentials (admin-only view)
 */
export type OAuthConfigConfig = {
  clientId?: string | undefined;
  clientSecret?: string | undefined;
  tenantId?: string | undefined;
};

export const OAuthConfigConfig$zodSchema: z.ZodType<OAuthConfigConfig> = z
  .object({
    clientId: z.string().optional(),
    clientSecret: z.string().optional(),
    tenantId: z.string().optional(),
  }).describe("OAuth credentials (admin-only view)");

/**
 * OAuth configuration for a connector type. Created by admins to enable
 *
 * @remarks
 * OAuth authentication for connectors.
 */
export type OAuthConfig = {
  configId?: string | undefined;
  connectorType?: string | undefined;
  oauthInstanceName?: string | undefined;
  orgId?: string | undefined;
  createdBy?: string | undefined;
  config?: OAuthConfigConfig | undefined;
  baseUrl?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const OAuthConfig$zodSchema: z.ZodType<OAuthConfig> = z.object({
  baseUrl: z.string().optional(),
  config: z.lazy(() => OAuthConfigConfig$zodSchema).optional(),
  configId: z.string().optional(),
  connectorType: z.string().optional(),
  createdAt: z.iso.datetime({ offset: true }).optional(),
  createdBy: z.string().optional(),
  oauthInstanceName: z.string().optional(),
  orgId: z.string().optional(),
  updatedAt: z.iso.datetime({ offset: true }).optional(),
}).describe(
  "OAuth configuration for a connector type. Created by admins to enable\nOAuth authentication for connectors.\n",
);
