/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * OAuth 2.0 Token Response (RFC 6749 Section 5.1).
 *
 * @remarks
 * Contains the access token and optional refresh/ID tokens.
 */
export type OAuthTokenResponse = {
  access_token?: string | undefined;
  token_type?: string | undefined;
  expires_in?: number | undefined;
  refresh_token?: string | undefined;
  scope?: string | undefined;
  id_token?: string | undefined;
};

export const OAuthTokenResponse$zodSchema: z.ZodType<OAuthTokenResponse> = z
  .object({
    access_token: z.string().optional(),
    expires_in: z.int().optional(),
    id_token: z.string().optional(),
    refresh_token: z.string().optional(),
    scope: z.string().optional(),
    token_type: z.string().optional(),
  }).describe(
    "OAuth 2.0 Token Response (RFC 6749 Section 5.1).\nContains the access token and optional refresh/ID tokens.\n",
  );
