/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * OpenID Connect UserInfo Response.
 *
 * @remarks
 * Contains claims about the authenticated user.
 */
export type OAuthUserInfoResponse = {
  user_id: string;
  name?: string | undefined;
  given_name?: string | undefined;
  family_name?: string | undefined;
  email?: string | undefined;
  email_verified?: boolean | undefined;
  picture?: string | undefined;
  updated_at?: number | undefined;
};

export const OAuthUserInfoResponse$zodSchema: z.ZodType<OAuthUserInfoResponse> =
  z.object({
    email: z.string().optional(),
    email_verified: z.boolean().optional(),
    family_name: z.string().optional(),
    given_name: z.string().optional(),
    name: z.string().optional(),
    picture: z.string().optional(),
    updated_at: z.int().optional(),
    user_id: z.string(),
  }).describe(
    "OpenID Connect UserInfo Response.\nContains claims about the authenticated user.\n",
  );
