/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request to exchange OAuth authorization code for tokens
 */
export type OAuthExchangeRequest = {
  code: string;
  email: string;
  provider: string;
  redirectUri: string;
};

export const OAuthExchangeRequest$zodSchema: z.ZodType<OAuthExchangeRequest> = z
  .object({
    code: z.string(),
    email: z.string(),
    provider: z.string(),
    redirectUri: z.string(),
  }).describe("Request to exchange OAuth authorization code for tokens");
