/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * OAuth 2.0 Token Introspection Response (RFC 7662).
 *
 * @remarks
 * Contains token metadata if active, or just `active: false` if not.
 */
export type OAuthIntrospectResponse = {
  active: boolean;
  scope?: string | undefined;
  client_id?: string | undefined;
  username?: string | undefined;
  token_type?: string | undefined;
  exp?: number | undefined;
  iat?: number | undefined;
  nbf?: number | undefined;
  user_id?: string | undefined;
  aud?: string | undefined;
  iss?: string | undefined;
  jti?: string | undefined;
};

export const OAuthIntrospectResponse$zodSchema: z.ZodType<
  OAuthIntrospectResponse
> = z.object({
  active: z.boolean(),
  aud: z.string().optional(),
  client_id: z.string().optional(),
  exp: z.int().optional(),
  iat: z.int().optional(),
  iss: z.string().optional(),
  jti: z.string().optional(),
  nbf: z.int().optional(),
  scope: z.string().optional(),
  token_type: z.string().optional(),
  user_id: z.string().optional(),
  username: z.string().optional(),
}).describe(
  "OAuth 2.0 Token Introspection Response (RFC 7662).\nContains token metadata if active, or just `active: false` if not.\n",
);
