/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  OAuthErrorResponse,
  OAuthErrorResponse$zodSchema,
} from "./oautherrorresponse.js";
import {
  OAuthIntrospectResponse,
  OAuthIntrospectResponse$zodSchema,
} from "./oauthintrospectresponse.js";

export type OauthIntrospectResponseResponse =
  | OAuthIntrospectResponse
  | OAuthErrorResponse;

export const OauthIntrospectResponseResponse$zodSchema: z.ZodType<
  OauthIntrospectResponseResponse
> = z.union([
  OAuthIntrospectResponse$zodSchema,
  OAuthErrorResponse$zodSchema,
]);
