/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Error code. Common values:
 *
 * @remarks
 * - `invalid_request` - Missing or invalid parameter
 * - `invalid_client` - Client authentication failed
 * - `invalid_grant` - Invalid authorization code or refresh token
 * - `unauthorized_client` - Client not authorized for this grant type
 * - `unsupported_grant_type` - Grant type not supported
 * - `invalid_scope` - Requested scope is invalid or exceeds allowed
 * - `access_denied` - User denied authorization
 */
export const ErrorT = {
  InvalidRequest: "invalid_request",
  InvalidClient: "invalid_client",
  InvalidGrant: "invalid_grant",
  UnauthorizedClient: "unauthorized_client",
  UnsupportedGrantType: "unsupported_grant_type",
  InvalidScope: "invalid_scope",
  AccessDenied: "access_denied",
  ServerError: "server_error",
} as const;
/**
 * Error code. Common values:
 *
 * @remarks
 * - `invalid_request` - Missing or invalid parameter
 * - `invalid_client` - Client authentication failed
 * - `invalid_grant` - Invalid authorization code or refresh token
 * - `unauthorized_client` - Client not authorized for this grant type
 * - `unsupported_grant_type` - Grant type not supported
 * - `invalid_scope` - Requested scope is invalid or exceeds allowed
 * - `access_denied` - User denied authorization
 */
export type ErrorT = ClosedEnum<typeof ErrorT>;

export const ErrorT$zodSchema = z.enum([
  "invalid_request",
  "invalid_client",
  "invalid_grant",
  "unauthorized_client",
  "unsupported_grant_type",
  "invalid_scope",
  "access_denied",
  "server_error",
]).describe(
  "Error code. Common values:\n- `invalid_request` - Missing or invalid parameter\n- `invalid_client` - Client authentication failed\n- `invalid_grant` - Invalid authorization code or refresh token\n- `unauthorized_client` - Client not authorized for this grant type\n- `unsupported_grant_type` - Grant type not supported\n- `invalid_scope` - Requested scope is invalid or exceeds allowed\n- `access_denied` - User denied authorization\n",
);

/**
 * OAuth 2.0 Error Response (RFC 6749 Section 5.2).
 *
 * @remarks
 * Standard error format for OAuth endpoints.
 */
export type OAuthErrorResponse = {
  error: ErrorT;
  error_description?: string | undefined;
  error_uri?: string | undefined;
  state?: string | undefined;
};

export const OAuthErrorResponse$zodSchema: z.ZodType<OAuthErrorResponse> = z
  .object({
    error: ErrorT$zodSchema,
    error_description: z.string().optional(),
    error_uri: z.string().optional(),
    state: z.string().optional(),
  }).describe(
    "OAuth 2.0 Error Response (RFC 6749 Section 5.2).\nStandard error format for OAuth endpoints.\n",
  );
