/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  OAuthErrorResponse,
  OAuthErrorResponse$zodSchema,
} from "./oautherrorresponse.js";

/**
 * Must be "code" for authorization code grant
 */
export const ResponseType = {
  Code: "code",
} as const;
/**
 * Must be "code" for authorization code grant
 */
export type ResponseType = ClosedEnum<typeof ResponseType>;

export const ResponseType$zodSchema = z.enum([
  "code",
]).describe("Must be \"code\" for authorization code grant");

/**
 * PKCE method (S256 recommended)
 */
export const OauthAuthorizeCodeChallengeMethod = {
  S256: "S256",
  Plain: "plain",
} as const;
/**
 * PKCE method (S256 recommended)
 */
export type OauthAuthorizeCodeChallengeMethod = ClosedEnum<
  typeof OauthAuthorizeCodeChallengeMethod
>;

export const OauthAuthorizeCodeChallengeMethod$zodSchema = z.enum([
  "S256",
  "plain",
]).describe("PKCE method (S256 recommended)");

export type OauthAuthorizeRequest = {
  response_type: ResponseType;
  client_id: string;
  redirect_uri: string;
  scope: string;
  state: string;
  code_challenge?: string | undefined;
  code_challenge_method?: OauthAuthorizeCodeChallengeMethod | undefined;
  nonce?: string | undefined;
};

export const OauthAuthorizeRequest$zodSchema: z.ZodType<OauthAuthorizeRequest> =
  z.object({
    client_id: z.string().describe("OAuth app client ID"),
    code_challenge: z.string().describe(
      "PKCE code challenge (base64url-encoded)",
    ).optional(),
    code_challenge_method: OauthAuthorizeCodeChallengeMethod$zodSchema
      .optional(),
    nonce: z.string().describe("Nonce for ID token binding").optional(),
    redirect_uri: z.string().describe(
      "Callback URI (must match registered URI)",
    ),
    response_type: ResponseType$zodSchema,
    scope: z.string().describe("Space-separated list of requested scopes"),
    state: z.string().describe("Random string for CSRF protection"),
  });

export type OauthAuthorizeResponse = {
  Headers: { [k: string]: Array<string> };
  Result?: OAuthErrorResponse | undefined;
};

export const OauthAuthorizeResponse$zodSchema: z.ZodType<
  OauthAuthorizeResponse
> = z.object({
  Headers: z.record(z.string(), z.array(z.string())).default({}),
  Result: OAuthErrorResponse$zodSchema.optional(),
});
