/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Information about an OAuth scope
 */
export type OAuthScopeInfo = {
  name?: string | undefined;
  description?: string | undefined;
  category?: string | undefined;
};

export const OAuthScopeInfo$zodSchema: z.ZodType<OAuthScopeInfo> = z.object({
  category: z.string().optional(),
  description: z.string().optional(),
  name: z.string().optional(),
}).describe("Information about an OAuth scope");
