/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Hint about token type (optional, improves performance)
 */
export const OAuthRevokeRequestTokenTypeHint = {
  AccessToken: "access_token",
  RefreshToken: "refresh_token",
} as const;
/**
 * Hint about token type (optional, improves performance)
 */
export type OAuthRevokeRequestTokenTypeHint = ClosedEnum<
  typeof OAuthRevokeRequestTokenTypeHint
>;

export const OAuthRevokeRequestTokenTypeHint$zodSchema = z.enum([
  "access_token",
  "refresh_token",
]).describe("Hint about token type (optional, improves performance)");

/**
 * OAuth 2.0 Token Revocation Request (RFC 7009).
 *
 * @remarks
 * Revokes an access or refresh token.
 */
export type OAuthRevokeRequest = {
  token: string;
  token_type_hint?: OAuthRevokeRequestTokenTypeHint | undefined;
  client_id: string;
  client_secret?: string | undefined;
};

export const OAuthRevokeRequest$zodSchema: z.ZodType<OAuthRevokeRequest> = z
  .object({
    client_id: z.string(),
    client_secret: z.string().optional(),
    token: z.string(),
    token_type_hint: OAuthRevokeRequestTokenTypeHint$zodSchema.optional(),
  }).describe(
    "OAuth 2.0 Token Revocation Request (RFC 7009).\nRevokes an access or refresh token.\n",
  );
