/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const OnceScheduleConfigScheduleType = {
  Once: "once",
} as const;
export type OnceScheduleConfigScheduleType = ClosedEnum<
  typeof OnceScheduleConfigScheduleType
>;

export const OnceScheduleConfigScheduleType$zodSchema = z.enum([
  "once",
]);

/**
 * Run crawling job once at a specific future datetime
 */
export type OnceScheduleConfig = {
  scheduleType: OnceScheduleConfigScheduleType;
  isEnabled?: boolean | undefined;
  timezone?: string | undefined;
  scheduledTime: string;
};

export const OnceScheduleConfig$zodSchema: z.ZodType<OnceScheduleConfig> = z
  .object({
    isEnabled: z.boolean().default(true),
    scheduleType: OnceScheduleConfigScheduleType$zodSchema,
    scheduledTime: z.iso.datetime({ offset: true }),
    timezone: z.string().default("UTC"),
  }).describe("Run crawling job once at a specific future datetime");
