/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of account
 */
export const OrganizationAccountType = {
  Individual: "individual",
  Business: "business",
} as const;
/**
 * Type of account
 */
export type OrganizationAccountType = ClosedEnum<
  typeof OrganizationAccountType
>;

export const OrganizationAccountType$zodSchema = z.enum([
  "individual",
  "business",
]).describe("Type of account");

/**
 * Onboarding status
 */
export const OnBoardingStatus = {
  Configured: "configured",
  NotConfigured: "notConfigured",
  Skipped: "skipped",
} as const;
/**
 * Onboarding status
 */
export type OnBoardingStatus = ClosedEnum<typeof OnBoardingStatus>;

export const OnBoardingStatus$zodSchema = z.enum([
  "configured",
  "notConfigured",
  "skipped",
]).describe("Onboarding status");

export type Organization = {
  _id?: string | undefined;
  slug?: string | undefined;
  registeredName?: string | undefined;
  shortName?: string | undefined;
  domain: string;
  contactEmail: string;
  accountType: OrganizationAccountType;
  onBoardingStatus?: OnBoardingStatus | undefined;
  isDeleted?: boolean | undefined;
  createdAt?: number | undefined;
  updatedAt?: number | undefined;
};

export const Organization$zodSchema: z.ZodType<Organization> = z.object({
  _id: z.string().optional(),
  accountType: OrganizationAccountType$zodSchema,
  contactEmail: z.string(),
  createdAt: z.int().optional(),
  domain: z.string(),
  isDeleted: z.boolean().default(false),
  onBoardingStatus: OnBoardingStatus$zodSchema.optional(),
  registeredName: z.string().optional(),
  shortName: z.string().optional(),
  slug: z.string().optional(),
  updatedAt: z.int().optional(),
});
