/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Credentials for OTP authentication
 */
export type OtpCredentials = { otp: string };

export const OtpCredentials$zodSchema: z.ZodType<OtpCredentials> = z.object({
  otp: z.string(),
}).describe("Credentials for OTP authentication");
