/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request to generate and send OTP
 */
export type OtpGenerateRequest = {
  email: string;
  cfTurnstileResponse?: string | undefined;
};

export const OtpGenerateRequest$zodSchema: z.ZodType<OtpGenerateRequest> = z
  .object({
    cfTurnstileResponse: z.string().optional(),
    email: z.string(),
  }).describe("Request to generate and send OTP");
