/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PaginationInfo = {
  page?: number | undefined;
  limit?: number | undefined;
  totalCount?: number | undefined;
  totalPages?: number | undefined;
};

export const PaginationInfo$zodSchema: z.ZodType<PaginationInfo> = z.object({
  limit: z.int().optional(),
  page: z.int().optional(),
  totalCount: z.int().optional(),
  totalPages: z.int().optional(),
});
