/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Credentials for password authentication
 */
export type PasswordCredentials = { password: string };

export const PasswordCredentials$zodSchema: z.ZodType<PasswordCredentials> = z
  .object({
    password: z.string(),
  }).describe("Credentials for password authentication");
