/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Response after successful password reset
 */
export type PasswordResetResponse = {
  data?: string | undefined;
  accessToken?: string | undefined;
};

export const PasswordResetResponse$zodSchema: z.ZodType<PasswordResetResponse> =
  z.object({
    accessToken: z.string().optional(),
    data: z.string().optional(),
  }).describe("Response after successful password reset");
