/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Platform-wide configuration settings for file uploads and feature toggles
 */
export type PlatformSettings = {
  fileUploadMaxSizeBytes: number;
  featureFlags: { [k: string]: boolean };
  updatedAt?: string | undefined;
};

export const PlatformSettings$zodSchema: z.ZodType<PlatformSettings> = z.object(
  {
    featureFlags: z.record(z.string(), z.boolean()),
    fileUploadMaxSizeBytes: z.int(),
    updatedAt: z.iso.datetime({ offset: true }).optional(),
  },
).describe(
  "Platform-wide configuration settings for file uploads and feature toggles",
);
