/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PaginationInfo, PaginationInfo$zodSchema } from "./paginationinfo.js";
import { RecordT, RecordT$zodSchema } from "./record.js";

/**
 * Currently applied filters
 */
export type Applied = {};

export const Applied$zodSchema: z.ZodType<Applied> = z.object({}).describe(
  "Currently applied filters",
);

/**
 * Available filter options with counts
 */
export type Available = {};

export const Available$zodSchema: z.ZodType<Available> = z.object({}).describe(
  "Available filter options with counts",
);

export type RecordsResponseFilters = {
  applied?: Applied | undefined;
  available?: Available | undefined;
};

export const RecordsResponseFilters$zodSchema: z.ZodType<
  RecordsResponseFilters
> = z.object({
  applied: z.lazy(() => Applied$zodSchema).optional(),
  available: z.lazy(() => Available$zodSchema).optional(),
});

/**
 * Paginated response for records listing
 */
export type RecordsResponse = {
  records?: Array<RecordT> | undefined;
  pagination?: PaginationInfo | undefined;
  filters?: RecordsResponseFilters | undefined;
};

export const RecordsResponse$zodSchema: z.ZodType<RecordsResponse> = z.object({
  filters: z.lazy(() => RecordsResponseFilters$zodSchema).optional(),
  pagination: PaginationInfo$zodSchema.optional(),
  records: z.array(RecordT$zodSchema).optional(),
}).describe("Paginated response for records listing");
