/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import {
  RefreshTokenResponse,
  RefreshTokenResponse$zodSchema,
} from "./refreshtokenresponse.js";

export type RefreshTokenSecurity = { scopedToken: string };

export const RefreshTokenSecurity$zodSchema: z.ZodType<RefreshTokenSecurity> = z
  .object({
    scopedToken: z.string().describe(
      "Scoped JWT token for service-to-service authentication.\nFormat: \"Bearer {scoped_token}\"\nRequired scopes vary by endpoint.\n",
    ),
  });

export type RefreshTokenResponseResponse = RefreshTokenResponse | AuthError;

export const RefreshTokenResponseResponse$zodSchema: z.ZodType<
  RefreshTokenResponseResponse
> = z.union([
  RefreshTokenResponse$zodSchema,
  AuthError$zodSchema,
]);
