/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Filters, Filters$zodSchema } from "./filters.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type RegenerateAgentAnswerSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const RegenerateAgentAnswerSecurity$zodSchema: z.ZodType<
  RegenerateAgentAnswerSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

/**
 * Request payload
 */
export type RegenerateAgentAnswerRequestBody = {
  filters?: Filters | undefined;
  modelKey?: string | undefined;
  chatMode?: string | undefined;
};

export const RegenerateAgentAnswerRequestBody$zodSchema: z.ZodType<
  RegenerateAgentAnswerRequestBody
> = z.object({
  chatMode: z.string().optional(),
  filters: Filters$zodSchema.optional(),
  modelKey: z.string().optional(),
}).describe("Request payload");

export type RegenerateAgentAnswerRequest = {
  agentKey: string;
  conversationId: string;
  messageId: string;
  body?: RegenerateAgentAnswerRequestBody | undefined;
};

export const RegenerateAgentAnswerRequest$zodSchema: z.ZodType<
  RegenerateAgentAnswerRequest
> = z.object({
  agentKey: z.string(),
  body: z.lazy(() => RegenerateAgentAnswerRequestBody$zodSchema).optional(),
  conversationId: z.string(),
  messageId: z.string(),
});
