/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type ReindexRecordSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const ReindexRecordSecurity$zodSchema: z.ZodType<ReindexRecordSecurity> =
  z.object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

/**
 * Request payload
 */
export type ReindexRecordRequestBody = { depth?: number | undefined };

export const ReindexRecordRequestBody$zodSchema: z.ZodType<
  ReindexRecordRequestBody
> = z.object({
  depth: z.int().default(-1),
}).describe("Request payload");

export type ReindexRecordRequest = {
  recordId: string;
  body?: ReindexRecordRequestBody | undefined;
};

export const ReindexRecordRequest$zodSchema: z.ZodType<ReindexRecordRequest> = z
  .object({
    body: z.lazy(() => ReindexRecordRequestBody$zodSchema).optional(),
    recordId: z.string(),
  });
