/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import {
  PasswordResetResponse,
  PasswordResetResponse$zodSchema,
} from "./passwordresetresponse.js";

export type ResetPasswordWithTokenSecurity = { scopedToken: string };

export const ResetPasswordWithTokenSecurity$zodSchema: z.ZodType<
  ResetPasswordWithTokenSecurity
> = z.object({
  scopedToken: z.string().describe(
    "Scoped JWT token for service-to-service authentication.\nFormat: \"Bearer {scoped_token}\"\nRequired scopes vary by endpoint.\n",
  ),
});

export type ResetPasswordWithTokenResponse = PasswordResetResponse | AuthError;

export const ResetPasswordWithTokenResponse$zodSchema: z.ZodType<
  ResetPasswordWithTokenResponse
> = z.union([
  PasswordResetResponse$zodSchema,
  AuthError$zodSchema,
]);
