/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SaveConnectorFiltersRequest,
  SaveConnectorFiltersRequest$zodSchema,
} from "./saveconnectorfiltersrequest.js";

export type SaveConnectorFiltersRequestRequest = {
  connectorId: string;
  body: SaveConnectorFiltersRequest;
};

export const SaveConnectorFiltersRequestRequest$zodSchema: z.ZodType<
  SaveConnectorFiltersRequestRequest
> = z.object({
  body: SaveConnectorFiltersRequest$zodSchema,
  connectorId: z.string(),
});

/**
 * Filters saved
 */
export type SaveConnectorFiltersResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

export const SaveConnectorFiltersResponse$zodSchema: z.ZodType<
  SaveConnectorFiltersResponse
> = z.object({
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Filters saved");
