/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request to save filter selections for a connector
 */
export type SaveConnectorFiltersRequest = { filters: { [k: string]: any } };

export const SaveConnectorFiltersRequest$zodSchema: z.ZodType<
  SaveConnectorFiltersRequest
> = z.object({
  filters: z.record(z.string(), z.any()),
}).describe("Request to save filter selections for a connector");
