/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * OAuth 2.0 authentication with fine-grained scopes.
 *
 * @remarks
 * Supports authorization_code (with PKCE) and client_credentials flows.
 * OAuth tokens are Bearer JWTs — use the same Authorization header as regular tokens.
 */
export type SchemeOauth2 = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

export const SchemeOauth2$zodSchema: z.ZodType<SchemeOauth2> = z.object({
  clientID: z.string().describe(
    "OAuth 2.0 authentication with fine-grained scopes.\nSupports authorization_code (with PKCE) and client_credentials flows.\nOAuth tokens are Bearer JWTs — use the same Authorization header as regular tokens.\n client identifier",
  ),
  clientSecret: z.string().describe(
    "OAuth 2.0 authentication with fine-grained scopes.\nSupports authorization_code (with PKCE) and client_credentials flows.\nOAuth tokens are Bearer JWTs — use the same Authorization header as regular tokens.\n client secret",
  ),
  tokenURL: z.string().default("/api/v1/oauth/token").describe(
    "OAuth 2.0 authentication with fine-grained scopes.\nSupports authorization_code (with PKCE) and client_credentials flows.\nOAuth tokens are Bearer JWTs — use the same Authorization header as regular tokens.\n token URL",
  ),
}).describe(
  "OAuth 2.0 authentication with fine-grained scopes.\nSupports authorization_code (with PKCE) and client_credentials flows.\nOAuth tokens are Bearer JWTs — use the same Authorization header as regular tokens.\n",
);
