/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";
import { SearchResult, SearchResult$zodSchema } from "./searchresult.js";

export type SearchHistorySecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const SearchHistorySecurity$zodSchema: z.ZodType<SearchHistorySecurity> =
  z.object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

export type SearchHistoryRequest = {
  limit?: number | undefined;
  page?: number | undefined;
};

export const SearchHistoryRequest$zodSchema: z.ZodType<SearchHistoryRequest> = z
  .object({
    limit: z.int().default(10).describe("Number of results per page"),
    page: z.int().default(1).describe("Page number"),
  });

/**
 * Search history with pagination
 */
export type SearchHistoryResponse = {
  results?: Array<SearchResult> | undefined;
  total?: number | undefined;
  page?: number | undefined;
  limit?: number | undefined;
};

export const SearchHistoryResponse$zodSchema: z.ZodType<SearchHistoryResponse> =
  z.object({
    limit: z.int().optional(),
    page: z.int().optional(),
    results: z.array(SearchResult$zodSchema).optional(),
    total: z.int().optional(),
  }).describe("Search history with pagination");
