/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Additional metadata about the source
 */
export type SearchResultItemMetadata = {
  recordId?: string | undefined;
  recordName?: string | undefined;
  connectorName?: string | undefined;
  webUrl?: string | undefined;
  mimeType?: string | undefined;
};

export const SearchResultItemMetadata$zodSchema: z.ZodType<
  SearchResultItemMetadata
> = z.object({
  connectorName: z.string().optional(),
  mimeType: z.string().optional(),
  recordId: z.string().optional(),
  recordName: z.string().optional(),
  webUrl: z.string().optional(),
}).describe("Additional metadata about the source");

/**
 * A single matching chunk from semantic search
 */
export type SearchResultItem = {
  content?: string | undefined;
  chunkIndex?: number | undefined;
  citationType?: string | undefined;
  metadata?: SearchResultItemMetadata | undefined;
  score?: number | undefined;
};

export const SearchResultItem$zodSchema: z.ZodType<SearchResultItem> = z.object(
  {
    chunkIndex: z.int().optional(),
    citationType: z.string().optional(),
    content: z.string().optional(),
    metadata: z.lazy(() => SearchResultItemMetadata$zodSchema).optional(),
    score: z.number().optional(),
  },
).describe("A single matching chunk from semantic search");
