/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Filters, Filters$zodSchema } from "./filters.js";

/**
 * Request body for performing semantic search across the enterprise knowledge base.<br><br>
 *
 * @remarks
 * <b>How Semantic Search Works:</b><br>
 * <ol>
 * <li>Query is converted to vector embeddings</li>
 * <li>Similar content is found using vector similarity</li>
 * <li>Results are ranked by relevance score</li>
 * <li>Matching chunks with metadata are returned</li>
 * </ol>
 * <b>Filtering:</b><br>
 * Use filters to narrow search scope to specific apps or knowledge bases.
 */
export type SemanticSearchRequest = {
  query: string;
  filters?: Filters | undefined;
  limit?: number | undefined;
  modelKey?: string | undefined;
  modelName?: string | undefined;
  chatMode?: string | undefined;
};

export const SemanticSearchRequest$zodSchema: z.ZodType<SemanticSearchRequest> =
  z.object({
    chatMode: z.string().optional(),
    filters: Filters$zodSchema.optional(),
    limit: z.int().default(10),
    modelKey: z.string().optional(),
    modelName: z.string().optional(),
    query: z.string(),
  }).describe(
    "Request body for performing semantic search across the enterprise knowledge base.<br><br>\n<b>How Semantic Search Works:</b><br>\n<ol>\n<li>Query is converted to vector embeddings</li>\n<li>Similar content is found using vector similarity</li>\n<li>Results are ranked by relevance score</li>\n<li>Matching chunks with metadata are returned</li>\n</ol>\n<b>Filtering:</b><br>\nUse filters to narrow search scope to specific apps or knowledge bases.\n",
  );
