/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ModelType, ModelType$zodSchema } from "./modeltype.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type SetDefaultAIModelSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const SetDefaultAIModelSecurity$zodSchema: z.ZodType<
  SetDefaultAIModelSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type SetDefaultAIModelRequest = {
  modelType: ModelType;
  modelKey: string;
};

export const SetDefaultAIModelRequest$zodSchema: z.ZodType<
  SetDefaultAIModelRequest
> = z.object({
  modelKey: z.string(),
  modelType: ModelType$zodSchema,
});
