/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Permission level for shared users:
 *
 * @remarks
 * <ul>
 * <li><code>read</code> - Can view only</li>
 * <li><code>write</code> - Can add messages</li>
 * </ul>
 */
export const ShareRequestAccessLevel = {
  Read: "read",
  Write: "write",
} as const;
/**
 * Permission level for shared users:
 *
 * @remarks
 * <ul>
 * <li><code>read</code> - Can view only</li>
 * <li><code>write</code> - Can add messages</li>
 * </ul>
 */
export type ShareRequestAccessLevel = ClosedEnum<
  typeof ShareRequestAccessLevel
>;

export const ShareRequestAccessLevel$zodSchema = z.enum([
  "read",
  "write",
]).describe(
  "Permission level for shared users:\n<ul>\n<li><code>read</code> - Can view only</li>\n<li><code>write</code> - Can add messages</li>\n</ul>\n",
);

/**
 * Request to share a conversation or search with other users
 */
export type ShareRequest = {
  userIds: Array<string>;
  accessLevel?: ShareRequestAccessLevel | undefined;
};

export const ShareRequest$zodSchema: z.ZodType<ShareRequest> = z.object({
  accessLevel: ShareRequestAccessLevel$zodSchema.default("read"),
  userIds: z.array(z.string()),
}).describe("Request to share a conversation or search with other users");
