/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SignInViaSAMLRequest = {
  email: string;
  sessionToken?: string | undefined;
};

export const SignInViaSAMLRequest$zodSchema: z.ZodType<SignInViaSAMLRequest> = z
  .object({
    email: z.string().describe("User's email address"),
    sessionToken: z.string().describe(
      "Session token from `/userAccount/initAuth`. Optional but recommended\nfor maintaining authentication state across the SAML flow.\n",
    ).optional(),
  });

export type SignInViaSAMLResponse = { Headers: { [k: string]: Array<string> } };

export const SignInViaSAMLResponse$zodSchema: z.ZodType<SignInViaSAMLResponse> =
  z.object({
    Headers: z.record(z.string(), z.array(z.string())).default({}),
  });
