/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * SMTP email server configuration for sending system emails (invitations, notifications, password resets)
 */
export type SMTPConfig = {
  host: string;
  port: number;
  username?: string | undefined;
  password?: string | undefined;
  fromEmail: string;
};

export const SMTPConfig$zodSchema: z.ZodType<SMTPConfig> = z.object({
  fromEmail: z.string(),
  host: z.string(),
  password: z.string().optional(),
  port: z.int(),
  username: z.string().optional(),
}).describe(
  "SMTP email server configuration for sending system emails (invitations, notifications, password resets)",
);
