/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * SAML SSO authentication configuration
 */
export type SSOAuthConfig = {
  entryPoint: string;
  certificate: string;
  emailKey: string;
};

export const SSOAuthConfig$zodSchema: z.ZodType<SSOAuthConfig> = z.object({
  certificate: z.string(),
  emailKey: z.string(),
  entryPoint: z.string(),
}).describe("SAML SSO authentication configuration");
