/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type StreamRecordBufferSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const StreamRecordBufferSecurity$zodSchema: z.ZodType<
  StreamRecordBufferSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type StreamRecordBufferRequest = {
  recordId: string;
  convertTo?: string | undefined;
};

export const StreamRecordBufferRequest$zodSchema: z.ZodType<
  StreamRecordBufferRequest
> = z.object({
  convertTo: z.string().describe("Target format for conversion").optional(),
  recordId: z.string().describe("Record ID"),
});
