/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { UserRole, UserRole$zodSchema } from "./userrole.js";

export type Team = {
  _id?: string | undefined;
  name: string;
  description?: string | undefined;
  orgId?: string | undefined;
  userRoles?: Array<UserRole> | undefined;
  createdAt?: number | undefined;
  updatedAt?: number | undefined;
};

export const Team$zodSchema: z.ZodType<Team> = z.object({
  _id: z.string().optional(),
  createdAt: z.int().optional(),
  description: z.string().optional(),
  name: z.string(),
  orgId: z.string().optional(),
  updatedAt: z.int().optional(),
  userRoles: z.array(UserRole$zodSchema).optional(),
});
