/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type ToggleMetricsCollectionSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const ToggleMetricsCollectionSecurity$zodSchema: z.ZodType<
  ToggleMetricsCollectionSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

/**
 * Request payload
 */
export type ToggleMetricsCollectionRequest = {
  enableMetricCollection: boolean;
};

export const ToggleMetricsCollectionRequest$zodSchema: z.ZodType<
  ToggleMetricsCollectionRequest
> = z.object({
  enableMetricCollection: z.boolean(),
}).describe("Request payload");

/**
 * Metrics collection toggled successfully
 */
export type ToggleMetricsCollectionResponse = { message?: string | undefined };

export const ToggleMetricsCollectionResponse$zodSchema: z.ZodType<
  ToggleMetricsCollectionResponse
> = z.object({
  message: z.string().optional(),
}).describe("Metrics collection toggled successfully");
