/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request to reset password using email token
 */
export type TokenPasswordResetRequest = { password: string };

export const TokenPasswordResetRequest$zodSchema: z.ZodType<
  TokenPasswordResetRequest
> = z.object({
  password: z.string(),
}).describe("Request to reset password using email token");
