/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorConfig,
  ConnectorConfig$zodSchema,
} from "./connectorconfig.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";
import {
  UpdateConnectorConfigRequest,
  UpdateConnectorConfigRequest$zodSchema,
} from "./updateconnectorconfigrequest.js";

export type UpdateConnectorConfigSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const UpdateConnectorConfigSecurity$zodSchema: z.ZodType<
  UpdateConnectorConfigSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type UpdateConnectorConfigRequestRequest = {
  connectorId: string;
  body: UpdateConnectorConfigRequest;
};

export const UpdateConnectorConfigRequestRequest$zodSchema: z.ZodType<
  UpdateConnectorConfigRequestRequest
> = z.object({
  body: UpdateConnectorConfigRequest$zodSchema,
  connectorId: z.string(),
});

/**
 * Configuration updated
 */
export type UpdateConnectorConfigResponse = {
  success?: boolean | undefined;
  config?: ConnectorConfig | undefined;
};

export const UpdateConnectorConfigResponse$zodSchema: z.ZodType<
  UpdateConnectorConfigResponse
> = z.object({
  config: ConnectorConfig$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("Configuration updated");
