/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorAuthConfig,
  ConnectorAuthConfig$zodSchema,
} from "./connectorauthconfig.js";

/**
 * Request to update authentication config (clears OAuth tokens, requires re-auth)
 */
export type UpdateConnectorAuthRequest = {
  auth: ConnectorAuthConfig;
  baseUrl?: string | undefined;
};

export const UpdateConnectorAuthRequest$zodSchema: z.ZodType<
  UpdateConnectorAuthRequest
> = z.object({
  auth: ConnectorAuthConfig$zodSchema,
  baseUrl: z.string().optional(),
}).describe(
  "Request to update authentication config (clears OAuth tokens, requires re-auth)",
);
