/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Action to perform on the step
 */
export const Action = {
  Complete: "complete",
  Skip: "skip",
} as const;
/**
 * Action to perform on the step
 */
export type Action = ClosedEnum<typeof Action>;

export const Action$zodSchema = z.enum([
  "complete",
  "skip",
]).describe("Action to perform on the step");

/**
 * Request payload
 */
export type UpdateOnboardingStatusRequest = { stepId: string; action: Action };

export const UpdateOnboardingStatusRequest$zodSchema: z.ZodType<
  UpdateOnboardingStatusRequest
> = z.object({
  action: Action$zodSchema,
  stepId: z.string(),
}).describe("Request payload");

/**
 * Onboarding status updated successfully
 */
export type UpdateOnboardingStatusResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  isOnboardingComplete?: boolean | undefined;
  nextStep?: string | undefined;
};

export const UpdateOnboardingStatusResponse$zodSchema: z.ZodType<
  UpdateOnboardingStatusResponse
> = z.object({
  isOnboardingComplete: z.boolean().optional(),
  message: z.string().optional(),
  nextStep: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Onboarding status updated successfully");
