/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";

/**
 * Authentication methods updated successfully
 */
export type UpdateAuthMethodResponseBody = { message?: string | undefined };

export const UpdateAuthMethodResponseBody$zodSchema: z.ZodType<
  UpdateAuthMethodResponseBody
> = z.object({
  message: z.string().optional(),
}).describe("Authentication methods updated successfully");

export type UpdateAuthMethodResponse = UpdateAuthMethodResponseBody | AuthError;

export const UpdateAuthMethodResponse$zodSchema: z.ZodType<
  UpdateAuthMethodResponse
> = z.union([
  z.lazy(() => UpdateAuthMethodResponseBody$zodSchema),
  AuthError$zodSchema,
]);
