/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { RecordT, RecordT$zodSchema } from "./record.js";

export type UpdateRecordFile = {
  fileName: string;
  content: Uint8Array | string;
};

export const UpdateRecordFile$zodSchema: z.ZodType<UpdateRecordFile> = z.object(
  {
    content: z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    fileName: z.string(),
  },
);

/**
 * Request payload
 */
export type UpdateRecordRequestBody = {
  recordName?: string | undefined;
  file?: UpdateRecordFile | Blob | undefined;
};

export const UpdateRecordRequestBody$zodSchema: z.ZodType<
  UpdateRecordRequestBody
> = z.object({
  file: z.lazy(() => UpdateRecordFile$zodSchema).optional(),
  recordName: z.string().optional(),
}).describe("Request payload");

export type UpdateRecordRequest = {
  recordId: string;
  body?: UpdateRecordRequestBody | undefined;
};

export const UpdateRecordRequest$zodSchema: z.ZodType<UpdateRecordRequest> = z
  .object({
    body: z.lazy(() => UpdateRecordRequestBody$zodSchema).optional(),
    recordId: z.string().describe("Record ID"),
  });

/**
 * Record updated successfully
 */
export type UpdateRecordResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  record?: RecordT | undefined;
};

export const UpdateRecordResponse$zodSchema: z.ZodType<UpdateRecordResponse> = z
  .object({
    message: z.string().optional(),
    record: RecordT$zodSchema.optional(),
    success: z.boolean().optional(),
  }).describe("Record updated successfully");
