/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorConfig,
  ConnectorConfig$zodSchema,
} from "./connectorconfig.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";
import {
  UpdateConnectorAuthRequest,
  UpdateConnectorAuthRequest$zodSchema,
} from "./updateconnectorauthrequest.js";

export type UpdateConnectorAuthConfigSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const UpdateConnectorAuthConfigSecurity$zodSchema: z.ZodType<
  UpdateConnectorAuthConfigSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type UpdateConnectorAuthConfigRequest = {
  connectorId: string;
  body: UpdateConnectorAuthRequest;
};

export const UpdateConnectorAuthConfigRequest$zodSchema: z.ZodType<
  UpdateConnectorAuthConfigRequest
> = z.object({
  body: UpdateConnectorAuthRequest$zodSchema,
  connectorId: z.string(),
});

/**
 * Auth configuration updated
 */
export type UpdateConnectorAuthConfigResponse = {
  success?: boolean | undefined;
  config?: ConnectorConfig | undefined;
};

export const UpdateConnectorAuthConfigResponse$zodSchema: z.ZodType<
  UpdateConnectorAuthConfigResponse
> = z.object({
  config: ConnectorConfig$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("Auth configuration updated");
