/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Updated provider configuration
 */
export type UpdateAIModelProviderRequestConfiguration = {};

export const UpdateAIModelProviderRequestConfiguration$zodSchema: z.ZodType<
  UpdateAIModelProviderRequestConfiguration
> = z.object({}).describe("Updated provider configuration");

/**
 * Request to update an existing AI model provider
 */
export type UpdateAIModelProviderRequest = {
  provider: string;
  configuration: UpdateAIModelProviderRequestConfiguration;
  isMultimodal?: boolean | undefined;
  isReasoning?: boolean | undefined;
  isDefault?: boolean | undefined;
  contextLength?: number | null | undefined;
};

export const UpdateAIModelProviderRequest$zodSchema: z.ZodType<
  UpdateAIModelProviderRequest
> = z.object({
  configuration: z.lazy(() =>
    UpdateAIModelProviderRequestConfiguration$zodSchema
  ),
  contextLength: z.int().nullable().optional(),
  isDefault: z.boolean().optional(),
  isMultimodal: z.boolean().optional(),
  isReasoning: z.boolean().optional(),
  provider: z.string(),
}).describe("Request to update an existing AI model provider");
