/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type UpdateKBPermissionsSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const UpdateKBPermissionsSecurity$zodSchema: z.ZodType<
  UpdateKBPermissionsSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export const UpdateKBPermissionsRole = {
  Owner: "OWNER",
  Organizer: "ORGANIZER",
  Fileorganizer: "FILEORGANIZER",
  Writer: "WRITER",
  Commenter: "COMMENTER",
  Reader: "READER",
} as const;
export type UpdateKBPermissionsRole = ClosedEnum<
  typeof UpdateKBPermissionsRole
>;

export const UpdateKBPermissionsRole$zodSchema = z.enum([
  "OWNER",
  "ORGANIZER",
  "FILEORGANIZER",
  "WRITER",
  "COMMENTER",
  "READER",
]);

/**
 * Request body for Update permissions
 */
export type UpdateKBPermissionsRequestBody = {
  userIds?: Array<string> | undefined;
  teamIds?: Array<string> | undefined;
  role: UpdateKBPermissionsRole;
};

export const UpdateKBPermissionsRequestBody$zodSchema: z.ZodType<
  UpdateKBPermissionsRequestBody
> = z.object({
  role: UpdateKBPermissionsRole$zodSchema,
  teamIds: z.array(z.string()).optional(),
  userIds: z.array(z.string()).optional(),
}).describe("Request body for Update permissions");

export type UpdateKBPermissionsRequest = {
  kbId: string;
  body: UpdateKBPermissionsRequestBody;
};

export const UpdateKBPermissionsRequest$zodSchema: z.ZodType<
  UpdateKBPermissionsRequest
> = z.object({
  body: z.lazy(() => UpdateKBPermissionsRequestBody$zodSchema),
  kbId: z.string(),
});
