/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type UpdateAgentSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const UpdateAgentSecurity$zodSchema: z.ZodType<UpdateAgentSecurity> = z
  .object({
    bearerAuth: z.string().describe(
      "JWT Bearer token for authenticated requests",
    ).optional(),
    oauth2: SchemeOauth2$zodSchema.optional(),
  });

export type UpdateAgentModelConfig = {};

export const UpdateAgentModelConfig$zodSchema: z.ZodType<
  UpdateAgentModelConfig
> = z.object({});

/**
 * Request body for Update agent
 */
export type UpdateAgentRequestBody = {
  name?: string | undefined;
  description?: string | undefined;
  systemPrompt?: string | undefined;
  tools?: Array<string> | undefined;
  knowledgeBases?: Array<string> | undefined;
  modelConfig?: UpdateAgentModelConfig | undefined;
  isPublic?: boolean | undefined;
};

export const UpdateAgentRequestBody$zodSchema: z.ZodType<
  UpdateAgentRequestBody
> = z.object({
  description: z.string().optional(),
  isPublic: z.boolean().optional(),
  knowledgeBases: z.array(z.string()).optional(),
  modelConfig: z.lazy(() => UpdateAgentModelConfig$zodSchema).optional(),
  name: z.string().optional(),
  systemPrompt: z.string().optional(),
  tools: z.array(z.string()).optional(),
}).describe("Request body for Update agent");

export type UpdateAgentRequest = {
  agentKey: string;
  body: UpdateAgentRequestBody;
};

export const UpdateAgentRequest$zodSchema: z.ZodType<UpdateAgentRequest> = z
  .object({
    agentKey: z.string(),
    body: z.lazy(() => UpdateAgentRequestBody$zodSchema),
  });
