/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorAuthConfig,
  ConnectorAuthConfig$zodSchema,
} from "./connectorauthconfig.js";
import {
  ConnectorFiltersConfig,
  ConnectorFiltersConfig$zodSchema,
} from "./connectorfiltersconfig.js";
import {
  ConnectorSyncConfig,
  ConnectorSyncConfig$zodSchema,
} from "./connectorsyncconfig.js";

/**
 * Request to update connector configuration (partial updates supported)
 */
export type UpdateConnectorConfigRequest = {
  auth?: ConnectorAuthConfig | undefined;
  sync?: ConnectorSyncConfig | undefined;
  filters?: ConnectorFiltersConfig | undefined;
  baseUrl?: string | undefined;
};

export const UpdateConnectorConfigRequest$zodSchema: z.ZodType<
  UpdateConnectorConfigRequest
> = z.object({
  auth: ConnectorAuthConfig$zodSchema.optional(),
  baseUrl: z.string().optional(),
  filters: ConnectorFiltersConfig$zodSchema.optional(),
  sync: ConnectorSyncConfig$zodSchema.optional(),
}).describe(
  "Request to update connector configuration (partial updates supported)",
);
