/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorFiltersConfig,
  ConnectorFiltersConfig$zodSchema,
} from "./connectorfiltersconfig.js";
import {
  ConnectorSyncConfig,
  ConnectorSyncConfig$zodSchema,
} from "./connectorsyncconfig.js";

/**
 * Request to update filters and sync config (connector must be authenticated and inactive)
 */
export type UpdateConnectorFiltersSyncRequest = {
  sync?: ConnectorSyncConfig | undefined;
  filters?: ConnectorFiltersConfig | undefined;
  baseUrl?: string | undefined;
};

export const UpdateConnectorFiltersSyncRequest$zodSchema: z.ZodType<
  UpdateConnectorFiltersSyncRequest
> = z.object({
  baseUrl: z.string().optional(),
  filters: ConnectorFiltersConfig$zodSchema.optional(),
  sync: ConnectorSyncConfig$zodSchema.optional(),
}).describe(
  "Request to update filters and sync config (connector must be authenticated and inactive)",
);
