/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type UpdateAgentTemplateSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const UpdateAgentTemplateSecurity$zodSchema: z.ZodType<
  UpdateAgentTemplateSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type UpdateAgentTemplateConfigSchema = {};

export const UpdateAgentTemplateConfigSchema$zodSchema: z.ZodType<
  UpdateAgentTemplateConfigSchema
> = z.object({});

/**
 * Request body for Update agent template
 */
export type UpdateAgentTemplateRequestBody = {
  name?: string | undefined;
  description?: string | undefined;
  category?: string | undefined;
  defaultSystemPrompt?: string | undefined;
  recommendedTools?: Array<string> | undefined;
  configSchema?: UpdateAgentTemplateConfigSchema | undefined;
  isPublic?: boolean | undefined;
};

export const UpdateAgentTemplateRequestBody$zodSchema: z.ZodType<
  UpdateAgentTemplateRequestBody
> = z.object({
  category: z.string().optional(),
  configSchema: z.lazy(() => UpdateAgentTemplateConfigSchema$zodSchema)
    .optional(),
  defaultSystemPrompt: z.string().optional(),
  description: z.string().optional(),
  isPublic: z.boolean().optional(),
  name: z.string().optional(),
  recommendedTools: z.array(z.string()).optional(),
}).describe("Request body for Update agent template");

export type UpdateAgentTemplateRequest = {
  templateId: string;
  body: UpdateAgentTemplateRequestBody;
};

export const UpdateAgentTemplateRequest$zodSchema: z.ZodType<
  UpdateAgentTemplateRequest
> = z.object({
  body: z.lazy(() => UpdateAgentTemplateRequestBody$zodSchema),
  templateId: z.string(),
});
