/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateToolsetConfigAuth = {};

export const UpdateToolsetConfigAuth$zodSchema: z.ZodType<
  UpdateToolsetConfigAuth
> = z.object({});

export type UpdateToolsetConfigRequestBody = {
  auth: UpdateToolsetConfigAuth;
  baseUrl?: string | undefined;
};

export const UpdateToolsetConfigRequestBody$zodSchema: z.ZodType<
  UpdateToolsetConfigRequestBody
> = z.object({
  auth: z.lazy(() => UpdateToolsetConfigAuth$zodSchema),
  baseUrl: z.string().optional(),
});

export type UpdateToolsetConfigRequest = {
  toolsetId: string;
  body: UpdateToolsetConfigRequestBody;
};

export const UpdateToolsetConfigRequest$zodSchema: z.ZodType<
  UpdateToolsetConfigRequest
> = z.object({
  body: z.lazy(() => UpdateToolsetConfigRequestBody$zodSchema),
  toolsetId: z.string(),
});
