/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request payload
 */
export type UpdateUserGroupRequestBody = {
  name?: string | undefined;
  description?: string | undefined;
};

export const UpdateUserGroupRequestBody$zodSchema: z.ZodType<
  UpdateUserGroupRequestBody
> = z.object({
  description: z.string().optional(),
  name: z.string().optional(),
}).describe("Request payload");

export type UpdateUserGroupRequest = {
  groupId: string;
  body: UpdateUserGroupRequestBody;
};

export const UpdateUserGroupRequest$zodSchema: z.ZodType<
  UpdateUserGroupRequest
> = z.object({
  body: z.lazy(() => UpdateUserGroupRequestBody$zodSchema),
  groupId: z.string().describe("Unique identifier of the user group to update"),
});
