/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { SchemeOauth2, SchemeOauth2$zodSchema } from "./schemeoauth2.js";

export type UploadRecordsToKBSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: SchemeOauth2 | undefined;
};

export const UploadRecordsToKBSecurity$zodSchema: z.ZodType<
  UploadRecordsToKBSecurity
> = z.object({
  bearerAuth: z.string().describe("JWT Bearer token for authenticated requests")
    .optional(),
  oauth2: SchemeOauth2$zodSchema.optional(),
});

export type UploadRecordsToKBFile = {
  fileName: string;
  content: Uint8Array | string;
};

export const UploadRecordsToKBFile$zodSchema: z.ZodType<UploadRecordsToKBFile> =
  z.object({
    content: z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    fileName: z.string(),
  });

/**
 * Request payload
 */
export type UploadRecordsToKBRequestBody = {
  files: Array<UploadRecordsToKBFile>;
  files_metadata?: string | undefined;
  isVersioned?: boolean | undefined;
  recordType?: string | undefined;
};

export const UploadRecordsToKBRequestBody$zodSchema: z.ZodType<
  UploadRecordsToKBRequestBody
> = z.object({
  files: z.array(z.lazy(() => UploadRecordsToKBFile$zodSchema)),
  files_metadata: z.string().optional(),
  isVersioned: z.boolean().default(true),
  recordType: z.string().default("FILE"),
}).describe("Request payload");

export type UploadRecordsToKBRequest = {
  kbId: string;
  body: UploadRecordsToKBRequestBody;
};

export const UploadRecordsToKBRequest$zodSchema: z.ZodType<
  UploadRecordsToKBRequest
> = z.object({
  body: z.lazy(() => UploadRecordsToKBRequestBody$zodSchema),
  kbId: z.string().describe("Knowledge base ID"),
});
