/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const UserBasicAccountType = {
  Individual: "individual",
  Business: "business",
} as const;
export type UserBasicAccountType = ClosedEnum<typeof UserBasicAccountType>;

export const UserBasicAccountType$zodSchema = z.enum([
  "individual",
  "business",
]);

/**
 * Basic user information
 */
export type UserBasic = {
  _id?: string | undefined;
  email?: string | undefined;
  fullName?: string | undefined;
  orgId?: string | undefined;
  accountType?: UserBasicAccountType | undefined;
};

export const UserBasic$zodSchema: z.ZodType<UserBasic> = z.object({
  _id: z.string().optional(),
  accountType: UserBasicAccountType$zodSchema.optional(),
  email: z.string().optional(),
  fullName: z.string().optional(),
  orgId: z.string().optional(),
}).describe("Basic user information");
