/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Group type:
 *
 * @remarks
 * - admin: System admin group (cannot be modified)
 * - standard: Default user group
 * - everyone: All users group (cannot be modified)
 * - custom: User-created custom group
 */
export const UserGroupType = {
  Admin: "admin",
  Standard: "standard",
  Everyone: "everyone",
  Custom: "custom",
} as const;
/**
 * Group type:
 *
 * @remarks
 * - admin: System admin group (cannot be modified)
 * - standard: Default user group
 * - everyone: All users group (cannot be modified)
 * - custom: User-created custom group
 */
export type UserGroupType = ClosedEnum<typeof UserGroupType>;

export const UserGroupType$zodSchema = z.enum([
  "admin",
  "standard",
  "everyone",
  "custom",
]).describe(
  "Group type:\n- admin: System admin group (cannot be modified)\n- standard: Default user group\n- everyone: All users group (cannot be modified)\n- custom: User-created custom group\n",
);

/**
 * User group for organizing users within an organization
 */
export type UserGroup = {
  _id?: string | undefined;
  slug?: string | undefined;
  type: UserGroupType;
  name: string;
  orgId: string;
  users?: Array<string> | undefined;
  isDeleted?: boolean | undefined;
  deletedBy?: string | undefined;
  createdAt?: number | undefined;
  updatedAt?: number | undefined;
};

export const UserGroup$zodSchema: z.ZodType<UserGroup> = z.object({
  _id: z.string().optional(),
  createdAt: z.int().optional(),
  deletedBy: z.string().optional(),
  isDeleted: z.boolean().default(false),
  name: z.string(),
  orgId: z.string(),
  slug: z.string().optional(),
  type: UserGroupType$zodSchema,
  updatedAt: z.int().optional(),
  users: z.array(z.string()).optional(),
}).describe("User group for organizing users within an organization");
