/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * User's role in the team
 */
export const UserRoleRole = {
  Owner: "OWNER",
  Reader: "READER",
} as const;
/**
 * User's role in the team
 */
export type UserRoleRole = ClosedEnum<typeof UserRoleRole>;

export const UserRoleRole$zodSchema = z.enum([
  "OWNER",
  "READER",
]).describe("User's role in the team");

export type UserRole = { userId: string; role: UserRoleRole };

export const UserRole$zodSchema: z.ZodType<UserRole> = z.object({
  role: UserRoleRole$zodSchema,
  userId: z.string(),
});
